### ISSUE TITLE
Should we move "Pending Questions" to the issue tracker?

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#1]
Would be easier to see what's been updated, so we know what requires our attention.  Also gives us an easy way to mark a question as "settled" and the add that decision to the wiki.

Thoughts?

**Comment by jabelch** [comment]
Having an issue brought to our attention is essential.  I don't want to muck around in a wiki or document each time just to see if there are changes embedded deep within.  I'm new to these systems, but if an 'issue tracker' holds up to its name, I like that.

**Comment by basepi** [comment]
Also, note that you can mention people (@Jzar, @jabelch, @BlackVegetable) to get people's attention as well.  =)

**Comment by basepi** [comment]
And subscribe or unsubscribe to specific issues.  I really like Github's issue tracker -- it's simple but effective.  =)

**Comment by jabelch** [comment]
We could use the issue tracker to ensure team input before final decisions, then once complete, make the changes in the wiki.
Or likewise, a change is made in the wiki, but then could be added here as well.

**Comment by basepi** [comment]
Obviously only major wiki changes require an issue -- as you can see you're probably getting e-mail notifications for changes on issues you've subscribed to.  So we don't want to spam each other endlessly.  (You can also change your notification settings so that it just notifies you at the top of the Github UI instead of e-mailing you)

**Comment by BlackVegetable** [comment]
Just noticed the potential spam issue...  I'll try to be more careful once I get the hang of this.

**Comment by basepi** [comment]
It's no problem.  I expect we'll all just change from "e-mail me!" to "notify me in Github!".

Also, for consistency, just mention everyone you need feedback from, instead of assigning one and mentioning the other.  Assigning an issue should be used just for things that are actually the responsibility of a single person.

**Comment by malikoth** [comment]
Yes.  Closing issue.
