### ISSUE TITLE
Capture State Change (server commands)

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#101]
Kyle mentioned a method for capturing state that involves saving any relevant server commands to a save file that can apply them on loading.  It could use a dictionary with the pane location as the key, which returns a list of relevant commands; monsters killed, treasures picked up, trees burned down, traps triggered, etc...

**Comment by BlackVegetable** [comment]
That could be a lot of commands.  All the same, let me know if you need help coming up with a list of such.

**Comment by BlackVegetable** [comment]
Is this issue still relevant?

**Comment by jabelch** [comment]
Nope, since we save off each pane that we visit, this isn't relevant
