### ISSUE TITLE
Display monster size

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#102]
@basepi 

One element of frustration for players will be to get in place to use a particular ability, only to discover that it won't work on the monster they were planning to target because that monster is too large or too small (based on a monster size variable.)  

We will have bars for health, mana, and AP for players, but we don't need AP bars for monsters.  Perhaps we could instead have a space for a single word indicating their size? (Small, Medium, Large, or Huge) Alternatively, if that would be difficult or unreadable at that size of font, perhaps we could have a differently colored bar that is more full if the monster is larger, and nearly empty if the monster is smaller?

**Comment by basepi** [comment]
The lack of an AP bar has allowed me to make monster unit frames much smaller, and still leave room for status effects.  That's what the rest of the space on those unit frames is reserved for, is status effects.  We could put size in there, but it would severely limit the number of stats effects that we could fit.  I'm open to suggestion, now that you can actually see the space available.

**Comment by BlackVegetable** [comment]
Maybe that isn't the right area to indicate size... An option would be to display the size of a monster via overlay when a button is pressed, or perhaps when selecting targets for an ability (via the colored overlay) but I feel the former option is better.  @Jzar, any thoughts?

**Comment by basepi** [comment]
Overlay would be fairly simple, just have to figure out how to integrate that into the current graphics engine API.

**Comment by BlackVegetable** [comment]
This can be done (in the meantime) with target selection and a button to display the size of the monster selected.

**Comment by BlackVegetable** [comment]
I think the monster level should be replaced with some characters indicating the monster size when a button is pressed to toggle this.  I can set up the button.  Once you have a way to replace the monsters levels with other text, I'll make a call to such a method when the button is pressed.  The text should be: SM for small, MD for medium, LG for large, and HG for huge. @basepi

**Comment by basepi** [comment]
Technically, this _could_ work right now just by passing in a monster level of "SM" or whatever.  Not ideal (as it's not intuitive) but you could do this now if you wanted.  Just a thought.  If that's repugnant, I'll implement some additional field ('size' or something), if it's a string i put it in place of the level, and if it's None, I don't.

**Comment by BlackVegetable** [comment]
That could work (the latter thing).  I'd rather not confuse myself in a month by trying to figure out why a monster has a string for a level.

**Comment by malikoth** [comment]
I vote overlay a single letter from [S, M, L, H] in the bottom left corner of the icon.  If possible, two copies of the letter.  One black, one blue maybe, with the colored one on top and offset a couple pixels on both axes, to help it stand out from the icon's coloring.

**Comment by BlackVegetable** [comment]
Of the monster's sprite?  Oh, you mean on the unit frame.  That wouldn't be a bad idea.

**Comment by basepi** [comment]
Nah, he meant on the sprite.  Though I like the unit frame better.  Methinks I will try making a small letter in the corner of the unit frame, and if that looks ugly or is unreadable, I'll move to the strategy we discussed previously, hitting a key to toggle between size and level.

I'm finding that 32x32 is actually super small.  To make an overlay letter readable, I think it would have to be big enough to be annoying.

**Comment by malikoth** [comment]
lol  No, I _DID_ mean on the unitframe.

**Comment by BlackVegetable** [comment]
Done.
