### ISSUE TITLE
Monster cannot enter combat with player

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#106]
If a monster moves to an adjacent tile, you don't enter into combat.

**Comment by BlackVegetable** [comment]
When we implement this, we need to check to see if they player is currently leveling up.  If so, we should not allow the monster to trigger combat.  There is a flag in game.py that can be checked by the client, but we'll need to communicate this to the server as well.

**Comment by BlackVegetable** [comment]
There are two flags in game.py that need to be checked: viewingInventory and performingLevelup.  Only the client sees them, so they'll need to be communicated to the server to prevent combat.  (Unless you think inventory browsing shouldn't protect you, but that will add logic on my part for editing things in combat, and we'll have to implement such after Beta.)

**Comment by BlackVegetable** [comment]
Moving this out of Beta, so as to keep Kyle from being overwhelmed.

**Comment by malikoth** [comment]
Agreed.

**Comment by malikoth** [comment]
I don't remember what the status of conversations on this topic are.  I'm kind of thinking we should allow monsters to initiate combat, which will dump you out of any dialog screen you're in.  Is the levelup dialog really so sacrosanct that we can't terminate it early?  What do you guys think?

**Comment by BlackVegetable** [comment]
Levelup is automatic now.  Being forced to enter levelup after battle and then being sucked into another battle while you cannot see due to being in a forced levelup screen would suck.  

Other screens, fine.  But levelup should make you immune to combat.

**Comment by malikoth** [comment]
Well, then I think we'll can this idea.  Because I don't want to have to communicate UI state to the server.  Sorry Josh!
