### ISSUE TITLE
In multiplayer, other players can't enter into combat.

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#107]
I think we discussed every player on the current pane would be pulled into combat when one player is.  Currently, when one player enters combat, other players cannot join (visually).  They either should be pulled into it automatically, or be able to join at their leisure.

This second option to join at their leisure might be better since a player that wasn't sucked into combat (perhaps they were off pane at the time) might be able to join in later.  If the monster doesn't move, the server should be able to add the joining player because the location will be the same.  The joining player will generate the same combat pane and the server will then display the monsters as they currently stand to that player.

**Comment by BlackVegetable** [comment]
The bug has changed somewhat, and now it seems to fail when a monster dies? or perhaps when cycling through targets right after a monster dies from another player.  In either case I think this is my issue to fix, but I would appreciate @Jzar 's help on it if I need it.

**Comment by BlackVegetable** [comment]
Fixed.
