### ISSUE TITLE
Seed needs to be sent to clients before world is created.

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#110]
As we discussed, the server needs to send the seed to all the clients... or clients need to request the seed as soon as they join.

**Comment by BlackVegetable** [comment]
As this doesn't crash the game, this should probably be pushed past Beta.  I'm going to move it out of this milestone, but feel free to move it back if you feel it belongs here.

**Comment by malikoth** [comment]
I'll get it done!  You'll see!  :)

**Comment by malikoth** [comment]
Done
