### ISSUE TITLE
Levelup Screens

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#116]
Need to be able to select new abilities and whatnot on levelup.

**Comment by BlackVegetable** [comment]
I'm going to need to know if you can automatically resize the images for this process or if you'll need me to create a bunch of different sizes of the ability icons.  Also, some icons need to be colored for this to be complete.

**Comment by basepi** [comment]
Almost certain I should be able to resize.  What size are the images now?

**Comment by BlackVegetable** [comment]
They are SVG, so they are whatever size you want them to be.  They need to be converted to PNG and some of them need coloring.

**Comment by basepi** [comment]
I would suggest converting them to PNG of size 48x48 or something.  Then I can resize from there.  I don't know what kind of support the PIL has for SVG

**Comment by BlackVegetable** [comment]
Probably not much.  I can convert them to 48x48, but I'll put that off for now.  Someone else may end up having free time and not knowing what their most productive task could be at that moment and they could take over the task.

**Comment by basepi** [comment]
Heh, won't be me.  =)

I plan to make it very modular -- something along the lines of you pass in a list of abilities with images, I pass back the index of the selected ability, or something like that.  So you not having the images ready will not affect me being able to create and test the screen.

**Comment by BlackVegetable** [comment]
Good to hear.  I might be able to recruit my wife to help with image resizing, actually.

**Comment by basepi** [comment]
Woot and whatnot.  =)

**Comment by basepi** [comment]
Done.
