### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#117]
Need to display contents of inventory, and allow player to equip items, use items, drop items, etc.

**Comment by basepi** [comment]
Probably should support quick-slotting

**Comment by BlackVegetable** [comment]
Quick slotting of items or the inventory?

**Comment by basepi** [comment]
Items in the inventory.  Specifically potions or something.  Maybe you could quickslot a couple of weapons, so you could switch between them.  Dunno.

**Comment by BlackVegetable** [comment]
I have planned on eventually adding quickslotting of two weapons, but honestly, I think the game would be more fun if you were stuck with whatever weapon you brought into combat.

**Comment by basepi** [comment]
Do we have potions besides mana and health?

**Comment by BlackVegetable** [comment]
Yes, do you need a list?

**Comment by basepi** [comment]
Nope.  When I implement the inventory screen, maybe we'll need to have some sort of flag as to whether an item can be quick-slotted.  Dunno.  Inventory is a few weeks off.

**Comment by basepi** [comment]
Have to do more welcome (once we get saving and loading in) and levelup and ability selection first, methinks.

**Comment by BlackVegetable** [comment]
This is done.
