### ISSUE TITLE
Shop UI

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#118]
Basically two-paned inventory, allowing items to be switched from one side to the other, etc.

**Comment by BlackVegetable** [comment]
What remains to be done for this?

**Comment by basepi** [comment]
## The UI is done, just needs the logic on the game side. 

Colton Myers

**Comment by BlackVegetable** [comment]
Alright.  Well, I shouldn't even start working on this until Josh/Kyle are close to having some kind of town at 0,0 at the very least.

**Comment by basepi** [comment]
## I suppose you could work on having the logic in place so it's ready for when the town is there. Dunno. 

Colton Myers

**Comment by basepi** [comment]
I'm closing this issue, as it's done as far as UI is concerned -- @BlackVegetable if you don't have one, you should create your own issue for the logic side of shops.
