### ISSUE TITLE
Player Status Screen

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#119]
Should show everything from unit frames, plus stats, maybe abilities, and definitely equipped items.  Only inter-actable part will be equipped items (to unequip them)

**Comment by BlackVegetable** [comment]
When you are looking for the stats to include, be sure to check the https://github.com/basepi/akintu/wiki/Attributes page to include the 6 primary attributes plus HP, MP, and max AP.

**Comment by BlackVegetable** [comment]
I will probably have a console-print version of the character sheet that you can use as a model for your real one set up in the next few days.  That way you can at least know which stats to include.

**Comment by basepi** [comment]
Woot!

**Comment by BlackVegetable** [comment]
The console version is done (I just have to push the latest version of it.)

**Comment by basepi** [comment]
This one is done on the GUI end.  Just needs game.py hooks, @BlackVegetable.
