### ISSUE TITLE
Overworld Obstacles overcome via spells or abilities

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#12]
Hey, this isn't really my area, but I'd like to know what kind of obstacles (underground rivers etc.) we would like to have in the game that will require items, spells or even abilities to overcome.  For example: there might be an underground lake blocking access to some treasure.  If you have a wizard that knows an underwater breathing spell, he can cast it on your party and you can continue.  Or perhaps there is something down a deep pit but you need rope to scale down there safely.  

What kinds of ideas do you guys have or want regarding this? @basepi @Jzar @jabelch

**Comment by basepi** [comment]
I vote doors (with keys or switches or something) are the only obstacles.  It makes things much simpler, and doesn't require you to roll certain abilities just to get past obstacles.  Doors could encompass a number of thing -- we can have puzzles that you have to get past to open doors, but I don't think anything should require a special item or ability that the dungeon doesn't provide for you.

**Comment by jabelch** [comment]
agreed. mostly.
Each dungeon will have everything it needs for your _successful_ completion.  But maybe further in the game you find a shovel that lets you go back to dig things up... or a candle that lets you burn things down.  These may reveal previously unknown parts of the game, or items, or monsters.

**Comment by basepi** [comment]
I suppose I'd be fine with stuff like that.  I personally do not like having to backtrack to a _different_ dungeon to get to places I couldn't before.  Backwards in the same dungeon is fine, but I like "finishing" dungeons and then moving on.  Just a personal preference, not necessarily "the right way".

**Comment by BlackVegetable** [comment]
I was thinking dungeons would occasionally have optional areas with modest treasures available for teams will a particular ability.  It wasn't meant to be a core progression tool.  Also, having many different ways to accomplish the same thing would be good.  The straightforward thing might be casting the Wizard spell.  Another option might be flipping the hidden switch that your Rogue found that drains the lake.  Another choice might be having your Fighter/Fighter class with massive constitution hold his breath and recover the treasure on his own.

I think overworld depth like this is going to be an important and appealing feature.

**Comment by basepi** [comment]
I can see this being cool.  There should definitely be a way for every class to get past these obstacles, though.  I would hate to have an area that was actually impossible to reach with a given class.  Easier with a given class, sure, but not impossible with another class.

This will probably present some challenges in world generation, FYI.  These obstacles would probably all have to be handcrafted and then randomly dropped in the world, just like we discussed with puzzles.

**Comment by BlackVegetable** [comment]
They wouldn't have to be terribly complex, but yeah.  We need some layers of creativity in our world or it won't seem terribly roguelike, in my opinion.

**Comment by malikoth** [comment]
So if I recall correctly, this idea is borrowed from Zelda.  The difference between Zelda and Akintu is that Zelda is pretty linear.  (I haven't played Zelda since I first discovered a gameboy emulator, so maybe newer Zeldas are less linear, idk)  There are so many dungeons in our dynamic on-the-fly world that I see no point in hiding content in one dungeon until later on.

On the other hand, I could see having obstacles that you have to find a tool inside that dungeon (or on that level) to be able to overcome.  And I like the idea of other obstacles that you have to use a class ability to overcome, as long as every class has something they can use here.  I think these could be pretty cool, let's do some.

**Comment by basepi** [comment]
I'm down.  I would push these to tier 2 or 3, for sure, though.
