### ISSUE TITLE
Ability selection overlay

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#121]
When a key is pressed, bring up ability selection.  Should probably allow quickslotting from this same screen.

**Comment by BlackVegetable** [comment]
I vote quickslots are #s 1-6 or something for abilities and spells.  We can use a couple of other buttons for potions.

**Comment by basepi** [comment]
probably 1-5, actually -- leaves a single line of buttons for quickslotting, and another line for the other buttons we'll need

**Comment by basepi** [comment]
Granted, the actually keybindings won't be in my hands.  I'll just provide an API to set those buttons to a given ability.

**Comment by basepi** [comment]
Finished.
