### ISSUE TITLE
Remove Kajhiit?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#123]
There are a few reasons why I'm considering removing this race from the game:

A) We don't have indoor/outdoor distinction, which makes up the most distinct part of this race.

B) It is extremely similar to the halfling otherwise.  The Halfling gets the +Sneak from its +Cunning.  The halfling has a slightly higher magic resist penalty.

C) The name is trademarked and would have to be changed if we ever pushed this game to greenlight or such.

D) I can't ever spell it's name correctly.

@Jzar and @basepi would have the most thoughts on this topic, I think.

**Comment by basepi** [comment]
Removing it will also remove any copyright problems.  I vote yes, remove it.

**Comment by malikoth** [comment]
Definitely yes.  Sorry for suggesting it, lol  It was funny at the time though
