### ISSUE TITLE
Back-door w\God Mode

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#127]
Currently player death is impossible.  Thus testing content or functionality doesn't depend on player skill.  However, once players can die, I think it would be vastly useful to have a "God-mode" that prevents player death.  This would need a back-door command line argument.  If we do it via command line, we need to be able to still select a class/race which means we can't skip the GUI if this argument is specified.

Is this worth it?
@jabelch @Jzar @basepi

**Comment by malikoth** [comment]
We could basically pass the server an update command to set a god-mode bit to 1.  Then in whatever routine updates HP in combat, only have it update your HP if player[command.id].godMode == 0  I agree that it would be worthwhile.

**Comment by basepi** [comment]
Or we could just have a specific name of a character be automatically god mode.  =)  An easter egg that a user could eventually find (though we should make the name sufficiently ridiculous to prevent easy discovery)

**Comment by BlackVegetable** [comment]
I like this plan.

**Comment by BlackVegetable** [comment]
We will have to have something to keep from killing the player off, by setting their minimum HP to a certain value.  To test some things, HP values need to be able to drop.  

Anyway, now we all need to start thinking of some names.  Oh, and it can''t be "jabelch" or "yourself" as those are already reserved.

**Comment by malikoth** [comment]
Rumpelstiltskin

**Comment by basepi** [comment]
Just set their max and current health to 100000000000000000000 or something.  ;-)  Super hacky, but super easy to implement, haha.

As far as names go, I've got nothing.

**Comment by BlackVegetable** [comment]
Onizuka was one my friend recommended.  It's a reference to a funny anime.

**Comment by BlackVegetable** [comment]
Okay, I'm choosing the name: RoNpAuL
If you have caps exactly like that, I'll assign you a passive ability that gives +10,000 HP.  This hasn't been implemented yet, but it will be.

**Comment by basepi** [comment]
## Bahahaha, your choice of name made me laugh out loud. =) 

Colton Myers

**Comment by malikoth** [comment]
If this is for "God" mode, shouldn't it be "mItT"?

**Comment by BlackVegetable** [comment]
Ugh, what a terrible joke!

**Comment by BlackVegetable** [comment]
Planned names (for beta testers, but we can keep them for release if you'd like:

RoNpAuL (+1,000 HP)
xkcd (+10,000 gold)

**Comment by BlackVegetable** [comment]
Implemented.
