### ISSUE TITLE
Game Difficulty Customization

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#13]
We have multiple mentions of Ironman mode and other difficulties through different topics.  I think it's important enough to have it's own space.

Some thoughts for discussion on menus and game customization:
1. Defaults that _most_ people will enjoy playing out of the box.  This doesn't mean perfect gameplay for everyone, nor does it mean we just enable easy mode (though it might end up being like that).
2. Simple difficulty selection - with complex customization.  I envision a menu that could have a selector of "Easy" through "Ironman", but it doesn't end there.  Those who want to customize individual categories can do so.  I always hated only being able to choose between easy, medium and hard - what about gold accrual or health regen rates, or the countless other choices.  
3. Character customization and map customization categories.  This becomes useful when playing multiplayer since we would want the host map's characteristics to apply.  The issue of how to resolve character inconsistencies will need to be discussed.  One possibility is to default to the strictest characteristics for everyone... appealing to the hardcore "purebloods", but destroying the livelihood of the hybrid "mudbloods".  Or, perhaps by separating the categories, the characters themselves can continue to function as originally chosen.

@jzar @blackvegetable @basepi

**Comment by basepi** [comment]
I don't know that we need to change anything for multiplayer.  The difficulty level will be decided by the host, and each character that joins will have his/her own characteristics (Ironman, hardcore, what have you) which shouldn't change.  This comes down to the fact that people can create multiple characters if they want different playstyles, and the fact that we want to allow the user to play the game how they want to.

As far as difficulty customization, I'm fine with this, though we want to avoid too much complexity for the end user.  Definitely those additional options should be in a completely separate "Advanced" menu.

**Comment by BlackVegetable** [comment]
Perhaps we can consider difficulty customization as a separate secondary (tertiary?) goal.  I think in general, to have the spirit of roguelikes, we should have the game pretty hard.  It already becomes massively easier with a softcore mode, and even easier with unlimited respec as an option.

**Comment by basepi** [comment]
I don't know that respec makes things easier, necessarily.  But softcore obviously does.  And in-depth customization should definitely be a tier 3 feature.

**Comment by malikoth** [comment]
As I discussed somewhere else, the player can choose their own difficulty basically by rushing through content so that they're fighting monsters at a higher level, or have a very easy experience if they just run around each level of a dungeon twice instead of once for some bonus xp, so they're always higher level than the monsters.  Other than that, roguelikes do tend to be pretty hard, and (other than the hardcore thing) I like it that way.

**Comment by BlackVegetable** [comment]
Agreed with Jzar.

**Comment by basepi** [comment]
Coolio.
