### ISSUE TITLE
Modifications to AI class

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#134]
Add chase / evade behaviors
Add compress / restore for game state preservation

**Comment by BlackVegetable** [comment]
Let me know if you would prefer implementing smarter path-finding or if I should.  The combat path-finding is really simple but the monster get stuck if they can't get around an object in one move.

**Comment by malikoth** [comment]
Maybe you should.  The AI class was more designed with overworld in mind anyways, and doesn't have the tools to deal with turntimers and AP restrictions, etc.

**Comment by BlackVegetable** [comment]
That's fine.  I'll just come up with some pathfinding for now.  If I feel really ambitious, I'll include fleeing behavior for some monsters as well.  It'd be nice to have some kind of threat-based system as well, but I don't see that happening during this semester.

**Comment by malikoth** [comment]
Done with compress / restore.
