### ISSUE TITLE
Add sound / music

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#136]

**Comment by malikoth** [comment]
Music is done!

**Comment by BlackVegetable** [comment]
And the music is great!

**Comment by BlackVegetable** [comment]
Moving this out of Beta, so as to keep Kyle from being overwhelmed.

**Comment by malikoth** [comment]
Agreed.

**Comment by malikoth** [comment]
Meh, sound is not coming.  This is as done as it's going to get.
