### ISSUE TITLE
Add selection, range, and aoe highlights

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#140]

**Comment by BlackVegetable** [comment]
Moving this out of Beta, so as to keep Kyle from being overwhelmed.

**Comment by malikoth** [comment]
I think this one is particularly important, because it's something very visual that makes combat a lot easier to understand.  I may not get it in time, and if that's the case, so be it.  But I'm still going to try.

**Comment by malikoth** [comment]
Leaving out aoe highlights for beta.  The other two are working pretty well now.  Still need to fix some logic for maintaining range highlights after manipulating selections.

**Comment by BlackVegetable** [comment]
The work done on my end for AoE highlights is sadly somewhat low on my list of priorities.  On that note, I'm moving this out of this milestone.

**Comment by malikoth** [comment]
Closing this.  The rework for location targeting will include the AoE highlights, and the other two have been completed.
