### ISSUE TITLE
Turn Timer Displayed

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#141]
This process begins with Colton adding the options in the starting screens.  Then it passes on to Devin or Kyle to store those settings somewhere associated with the character and with the server (for turn timer).  Then they've actually got to be implemented (Hardcore by Devin/Kyle, Ironman by Devin and Turn Timer again by Colton).

**Comment by BlackVegetable** [comment]
Alright, this has been added by Colton.  Should we put hardcore and ironman flags in the player character class?

**Comment by basepi** [comment]
Changed assignment to you, @BlackVegetable, as it's out of my hands now.

**Comment by BlackVegetable** [comment]
The settings for ironman and hardcore are now housed within a PlayerCharacter.  Turn timer has not been set yet.  @basepi when are you planning on adding a countdown timer to the UI?

**Comment by basepi** [comment]
Hrm....probably this weekend.  Planning on inventory/shop, then in-game menu, then UI timer.

**Comment by BlackVegetable** [comment]
So you do not plan on doing inventory until Saturday?  If you aren't planning on that, I will need to implement my own text based one in the meantime.

**Comment by basepi** [comment]
Erm, probably more like Thursday or Friday.  (In all reality, it will
probably be start on Thursday, finish on Friday)

## 

Colton Myers

**Comment by BlackVegetable** [comment]
Well, I'll still probably need to do this tomorrow.  Luckily some (most?) of the work I'll do will transfer over to any implementation that uses your UI.

**Comment by basepi** [comment]
Cool.

## 

Colton Myers

**Comment by BlackVegetable** [comment]
So, is Turn Timer going to be a feature for our Beta Demo @basepi ?

**Comment by basepi** [comment]
I can make it one, if it's a priority.

I'm going to send out a GUI priority e-mail.

**Comment by BlackVegetable** [comment]
If you have the turn timer GUI finished by Sunday afternoon, I should be able to have it integrated fully by Monday morning.

**Comment by basepi** [comment]
KK.  I expect it will just be a set_turn_timer() method, which takes a
float between 0.0 and 1.0 representing the percent of time left.

Unless you had something else in mind.

## 

Colton Myers

**Comment by BlackVegetable** [comment]
I am in favor of timer start and timer end methods.  The client can have its own timer that will not be authoritative.  I suppose the GUI shouldn't handle that detail but the client should. Why not an int for seconds left instead of that percent...OH.  You want a graphic.  That'll be neater.

**Comment by basepi** [comment]
## Ya, I envisioned a bar that depletes. =) 

Colton Myers

**Comment by BlackVegetable** [comment]
This is complete other than the UI part that Colton needs to do.  All the same, I'm removing this from our Beta milestone.

**Comment by basepi** [comment]
UI part done.  Just need to start calling screen.set_turntime(turntime)

**Comment by BlackVegetable** [comment]
@Jzar, do you want to take over having this displayed via servercombat.py?  I have some ideas on how to implement it if you need assistance.  If you have your hands full though, I'll handle it later.  This isn't urgent either way.

**Comment by basepi** [comment]
## If you haven't been following the conversation, it's implemented in the GUI already. I can give you a rundown if needed. 

Colton Myers

**Comment by malikoth** [comment]
Sure, I'll take it over.  However, just for the record, the server doesn't have ANYTHING to do with things that are displayed.  It goes in GAME.  If we don't already have something like a TURN_START command, or something equivalent, I'll add it.  Then the client can take any actions it wants to based on that.  And if the client's turn timer is off by the latency between the client and the server, maybe I'll subtract 2 \* RTT to make sure that any command issued before the client's version of the turn timer depletes will still arrive at the server before the turn ends.

**Comment by BlackVegetable** [comment]
Yeah, do that as you see fit.  I would place near-perfect synchronization of the server-timer and any client-timer as a very low priority.

**Comment by malikoth** [comment]
Same here, but I think that calculation should be fairly straightforward.  Even discovering the average RTT shouldn't be hard.

**Comment by malikoth** [comment]
Done.
