### ISSUE TITLE
Save/Load Game

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#142]
I will help you with this Josh, but you'll need to remind me of all the things you need.

**Comment by BlackVegetable** [comment]
This is going to have to be suitable for Beta.  I'm moving it off of the milestone.

**Comment by jabelch** [comment]
What do you mean by this?

**Comment by basepi** [comment]
He means we probably won't get any further than we currently are for beta.  What with bughunting.

**Comment by basepi** [comment]
(Don't know why I didn't just let him answer that question.....  =P  I'm probably wrong.)

**Comment by jabelch** [comment]
Save/Load works in general so I'll close this.  As we add things that need saving, open a new issue
