### ISSUE TITLE
Character sheed ("C" key) doesn't display gained experience

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#148]
This is after combat has finished and my console displayed that I gained 30 experience

/-------------------------------------------------------
| Character Name: test3
| Level: 1  Experience: 0/100
| Character Class: Assassin  Race: Elf
| HP: 54/54  MP: 0/0  AP: 20/20
| ----------->>> Primary Statistics <<<-----------------
| Strength: 12 (0)  Dexterity: 19 (0)
| Cunning:  17 (0)  Sorcery: 7 (0)
| Piety:    7 (0)  Constitution: 6 (0)
| ----------->>> Secondary Statistics <<<---------------
| Melee Accuracy:    16 (0)  Ranged Accuracy: 21 (0)
| Dodge:             19 (0)  Ranged Dodge: 0 (0)
| Might:             2 (0)  Melee Dodge: 0 (0)
| Spellpower:        7 (0)  Magic Resist: 7 (0)
| Critical Chance:   13.5% (0)  Critical Magnitude: 0% (0)
| Armor Penetration: 1.75% (0)  Damage Resistance: 0% (0)
| Poison Tolerance:  -5 (0)  Poison Rating Bonus: 0 (0)
| Awareness:         17 (0)  Sneak: 7 (0)
| Trap Evade:        17 (0)  Movement Tiles: 2 (0)
| ----------->>> Tertiary Statistics <<<----------------
| Shop Bonus:           3.5% (0%)  Carrying Capacity: 96 (0)
| Trap Rating Bonus:    0      Trap Damage Bonus: 0
| Jewlery Effect:       100%     Potion Bonus Effect: 0%
| Identification:       7 (0)
| ----------->>> Elemental Resistances <<<--------------
| Arcane Resistance:   0% (0)
| Cold Resistance:     0% (0)
| Divine Resistance:   0% (0)
| Electric Resistance: 0% (0)
| Fire Resistance:     0% (0)
| Poison Resistance:   0% (0)
| Shadow Resistance:   0% (0)
| ----------->>> Elemental Power <<<--------------------
| Arcane Damage Bonus:   0% (0)
| Cold Damage Bonus:     0% (0)
| Divine Damage Bonus:   0% (0)
| Electric Damage Bonus: 0% (0)
| Fire Damage Bonus:     0% (0)
| Poison Damage Bonus:   0% (0)
| Shadow Damage Bonus:   0% (0)
| ----------->>> Active Abilities <<<-------------------
| Level 1: Melee Attack AP: 6 Cooldown: 0
| Level 1: Ranged Attack AP: 5 Cooldown: 0
| Level 1: Assassin Stealth AP: 7 Cooldown: 3
| Level 1: Hidden Shot AP: 5 Cooldown: 2
| Level 1: Chain Grasp AP: 6 Cooldown: 7
| Level 1: Ranged Backstab AP: 10 Cooldown: 2
| ----------->>> Magic Spells <<<-----------------------
| ----------->>> Passive Abilities <<<------------------
| Level 1: Anatomy
-------------------------------------------------------

**Comment by BlackVegetable** [comment]
Fixed
