### ISSUE TITLE
Is cooldown supposed to carry over into new combat screens?

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#149]
I finished combat with one monster (group) and have now entered a new combat pane.  I am unable to use an ability and it is on cooldown for 2 more turns.  This may be a bug since the time between one combat pane to another could feasibly be quite long.

**Comment by BlackVegetable** [comment]
Aha! This is indeed a bug.  I will fix this.  Thank you!

**Comment by BlackVegetable** [comment]
Fixed
