### ISSUE TITLE
Hardcore Death Dialog

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#150]
Some sort of screen saying you've died in hardcore.  We will exit immediately afterwards.

**Comment by basepi** [comment]
I realized that we should just use the MenuDialog for this functionality.  Put "You Died!" or something as the top text, and "Exit" as the only option.

If that's not acceptable, @BlackVegetable, feel free to re-open this and I'll pump something out real quick.

**Comment by basepi** [comment]
Assigned to you, @BlackVegetable.

**Comment by BlackVegetable** [comment]
Done.
