### ISSUE TITLE
Broadcast error: index out of range

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#158]
1337 None {'seed': 'fdsa'} 004
Listening for clients...
Connecting to server...
Substituting 004 with 004_Dragon_Elf_Dragoon.akinc
Attempting to open res\saves\characters\004_Dragon_Elf_Dragoon.akinc
Connection made with client on port #3277
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Loading pane (0, 1)
Loading pane (0, 2)
Unloading pane (0, 0)
Attempting to save state on pane (0, 0)
as file: Pane_0_0
with data: {'chests': [], 'monsters': []}
Server error: Attempted to stop non-existent ai function: RUN
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 114, in serve
r_loop
    self.broadcast(Command("PERSON", "STOP", id=command.id), command.id)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 226, in broad
cast
    port = [p for p, i in self.player.iteritems() if i == pid][0]
exceptions.IndexError: list index out of range
ClientData lost connection.
ClientDataFactory lost connection.
ServerData lost connection to client on 3277.

**Comment by BlackVegetable** [comment]
Did this actually crash the game?

**Comment by jabelch** [comment]
I can't remember now

**Comment by jabelch** [comment]
Happened again: yes it did crash, AI stopped, pane switching stopped.  You can still move around in the current pane, I stopped it manually.

1337 None {'seed': 'fdsa'} 006
Listening for clients...
Connecting to server...
Substituting 006 with 006_D2_Elf_Dragoon.akinc
Attempting to open res\saves\characters\006_D2_Elf_Dragoon.akinc
Connection made with client on port #8808
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Loading pane (0, 1)
Connection made with client on port #8815
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Warning: Item added to inventory caused the inventory to exceed the MAX_SLOTS of
 20 items.
Server error: Attempted to stop non-existent ai function: RUN
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 114, in serve
r_loop
    self.broadcast(Command("PERSON", "STOP", id=command.id), command.id)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 226, in broad
cast
    port = [p for p, i in self.player.iteritems() if i == pid][0]
exceptions.IndexError: list index out of range

**Comment by malikoth** [comment]
I think this is fixed.  However, since I cannot duplicate the bug, I cannot confirm it.  Reopen if you see it again.
