### ISSUE TITLE
Dead Combat Panes after server calls unload_panes

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#159]
If you go far enough out to have server.py unload a pane, going into combat creates a "dead pane" where the entire combat pane is a dead zone and AP isn't deducted.

**Comment by jabelch** [comment]
If you go to pane (0, 3) then up to (0, 1), combat is broken in (0, 1)
If you go to pane (0, 3) then up to (0, 0), then down to (0, 1), combat works in (0, 1)

down to (0, 2), up to (0, 1) BROKEN
down to (0, 2), up to (0, 0) down to (0, 1) WORKS

Seems to be related to load_pane and unload_panes

**Comment by malikoth** [comment]
I won't tell you how embarrasingly easy this was to fix once I found my error.
