### ISSUE TITLE
Traps set by Hunters

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#16]
I have a question on the Traps page, but I'll just post it here:

Devin: Should Hunter primary classes require components to set traps in battle?  I vote yes.  However, the Tactician can set magical traps, which should not require components.  Thoughts?

@basepi @jabelch @Jzar

**Comment by malikoth** [comment]
On a related note, do you want to require players wielding ranged weapons to also have to carry a stack of appropriate ammunition?  I've always hated that part of Moria, as I don't feel like worrying about the number of arrows you have made it more fun, it was just an extra thing to worry about.  When I ran out of arrows at an inopportune time, I didn't feel like my subsequent death was fair.

So by the same reasoning, I vote that traps do not require components.  It seems that when we see traps in use in movies (see the Hunger Games), the trappers are not whipping out clawed bear traps and just plopping them on the ground, they're using their environment and whatever they can find at hand, and improvising.  This is how I imagine ranger traps.

**Comment by BlackVegetable** [comment]
Alright.  I hate having ammo with arrows anyway.  By that same note, I'm fine with no-ammo traps.

**Comment by basepi** [comment]
I agree.  I hate ammo.  Especially ammo that has weight and takes up carrying capacity.  (Played a game with my ex GF on the PS3 that was that way -- I never had any room in my inventory because I felt like I had to carry tons of arrows, and they weighed way more than they should)

Sorry about the tangent.  Imma close this.
