### ISSUE TITLE
Selecting items while Multiplayer battle ends

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#165]
If the player is in the middle of selecting a consumable to use when the battle ends, I'm not sure what will happen.  This is a similar issue to selecting an ability or spell when the battle ends though...

**Comment by BlackVegetable** [comment]
If this is an issue at all, it is within the realm of the keybinding world now.  Shifting to Jzar.

**Comment by malikoth** [comment]
lol  Well, I don't know for sure what it would do, either.  I put a call to self.screen.hide_dialog() in the command handler if combat=False is sent down, and that should close the dialog.  I don't know enough about dialogs to tell you if there's any corner cases or what happens to the gamescreen if you pane switch with a dialog up.  You should have a beta tester tell us!
