### ISSUE TITLE
combat death key error

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#166]
E:\Users\Josh\Documents\GitHub\akintu\src>python akintu.py
1337 None {'seed': 'fdsa'} ('JAB', 'Orc', 'Dragoon')
Listening for clients...
Connecting to server...
Connection made with client on port #16788
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Connection made with client on port #2520
Loading pane (-1, 0)
Loading pane ((-1, 0), (24, 8), 2)
Server error: Attempted to stop non-existent ai function: RUN
Server error: Attempted to stop non-existent ai function: RUN
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x099776B0>
None
False
None
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x099776B0>
None
False
None
<equipment.Weapon object at 0x099776B0>
None
False
Mysterious Adventurer has status: Mystic Shield T=4
Mysterious Adventurer has status: Mystic Shield T=3
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x099776B0>
None
False
None
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x099776B0>
None
False
None
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
Mysterious Adventurer has status: Mystic Shield T=2
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
Unloading pane ((-1, 0), (24, 8), 2)
Loading pane ((-1, 0), (26, 5), 2)
Server error: Attempted to stop non-existent ai function: RUN
Server error: Attempted to stop non-existent ai function: RUN
Unhandled Error
Traceback (most recent call last):
  File "akintu.py", line 54, in main
    hardcore=hardcore)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 113, in **init_
_
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 270, in
 check_turn_end
    for player in [self.server.person[x] for x in self.server.pane[combatPane].p
erson if x in
exceptions.KeyError: ((-1, 0), (24, 8), 2)
Mysterious Adventurer has status: Mystic Shield T=4
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x099776B0>
None
False
None
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x099776B0>
None
False
None
<equipment.Weapon object at 0x099776B0>
None
False
Mysterious Adventurer has status: Mystic Shield T=3
Mysterious Adventurer has status: Mystic Shield T=2
JAB has status: Howl T=4
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x099776B0>
None
False
None
<equipment.Weapon object at 0x099776B0>
None
False
<equipment.Weapon object at 0x099776B0>
None
False
None
<equipment.Weapon object at 0x099776B0>
None
False
Mysterious Adventurer has status: Mystic Shield T=1
Mysterious Adventurer has status: Howl T=4
JAB has status: Howl T=3
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
False
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
Mysterious Adventurer has status: Howl T=3
JAB has status: Howl T=2
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
False
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
Mysterious Adventurer has status: Howl T=2
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
Mysterious Adventurer has status: Howl T=1
Server error: Attempted to stop non-existent ai function: RUN
<equipment.Weapon object at 0x09998990>
<equipment.Armor object at 0x09998A10>
True
Unloading pane ((-1, 0), (26, 5), 2)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call**
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 132, in game_lo
op
    self.check_queue()
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 259, in check_q
ueue
    self.pane.person[command.id].removeClientStatus(command.status)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\person.py", line 267, in remov
eClientStatus
    del self._clientStatusView[statusName]
exceptions.KeyError: 'Howl'
Unhandled Error
Traceback (most recent call last):
  File "akintu.py", line 54, in main
    hardcore=hardcore)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 113, in __init_
_
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 270, in
 check_turn_end
    for player in [self.server.person[x] for x in self.server.pane[combatPane].p
erson if x in
exceptions.KeyError: ((-1, 0), (26, 5), 2)

**Comment by jabelch** [comment]
Kyle, When I died in combat, my image persisted on Devin's combat pane. 
After dying, I went back to combat and the server crashed

**Comment by jabelch** [comment]
Ok, so we did it again, I died, came back and we finished combat together without it crashing (we still got various keyerrors on line 270 of server combat).
Once we ended combat, Devin saw my character duplicated across panes every time he switched (approximately where I was when he left the pane).

**Comment by BlackVegetable** [comment]
Line 412 in monster_victory crashes with a key error even in singleplayer.

**Comment by malikoth** [comment]
Appears to be fixed.
