### ISSUE TITLE
Brewing Potions & Balancing Sorcery

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#17]
I have written up an example of how Brewing Potions could work on the brew potions page:

https://github.com/basepi/akintu/wiki/Brew-potions

I have a discussion section listed there, but let's just handle this one in the issue tracker.  Here are arguments for allowing this limited crafting system:
- It balances Sorcery and makes wizard-type classes more valuable.
- It adds depth to the gameplay
- It gives us a larger variety of loot to give to players (reagents are needed for potions.)
- It gives an additional use for gold (some potions convert raw gold coins as reagents for potions.)
- It keeps players from having to trek back to town as often.

Here is an alternative to this system:  Sorcery improves the amount that characters are affected by healing and mana potions.  It also slightly increases the duration of buffing potions.
- This also balances Sorcery.
- It makes moderate (and attainable) levels of Sorcery seem valuable to non Wizards.
- It saves us from the complexity of a crafting system.
- It seems more in line with our position of avoiding MMO-style crafting systems.

I am leaning toward the second choice, even though I originally proposed the first.  Ideas/Suggestions?

@basepi @jabelch @Jzar

**Comment by malikoth** [comment]
I actually don't have a problem with doing a crafting system, despite the fact that this isn't an MMO.  However, I think it would require a ton of work, and should be like, a Tier 3.5 feature, so I wouldn't want to count on getting it all done to balance any stats.  If we implement one crafting discipline, even limited in scope like brewing, it would feel strange to have no other options.  And it would make me feel compelled to level it on every character I could, which would be boring with no alternative disciplines to choose from instead.

Hence, I like the second proposal.  In addition to having sorcery scale health potion value, what about having it make healing spells cast on you do more healing as well?  Just an idea.

**Comment by BlackVegetable** [comment]
It already does that.

**Comment by BlackVegetable** [comment]
There may have been some confusion because the one healing spell I have done so far heals for a fixed amount.  Most healing spells will scale with spellpower which is created through Sorcery.

**Comment by BlackVegetable** [comment]
Actually, that isn't true.  The one healing spell does scale with Sorcery already.  Ignore that last comment.

**Comment by basepi** [comment]
I like the second idea as well.  And I agree with @Jzar, crafting should be tier 3 or 3.5, it will be tough with limited shock factor on demo day.

**Comment by malikoth** [comment]
Aight, tier 3.5 then?  (i.e., probably not going to get to)  Any other thoughts or comments?  If not in a couple more days, then someone just close this.

**Comment by basepi** [comment]
21 hours definitely == a couple more days.  CLOSING!
