### ISSUE TITLE
Multiplayer Turn timer is not correctly cancelled.

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#170]
Monsters seem to get a "free" turn sometimes because the turn timer is not correctly cancelled in multiplayer.  I'm not sure why that is.  Any help from @Jzar would be appreciated, but we'll probably have to put this off until after the Beta demo.  (The demo should have an unlimited turn timer, I think.)

**Comment by malikoth** [comment]
I took a guess at what the problem is, and put in a fix.  I think I'll go ahead and close this under the assumption that that fixes it.  Reopen as necessary.
