### ISSUE TITLE
Automatic Levelup

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#179]
In games like Torchlight and Diablo (1 & 2), you have levelup icons that become available when you have earned enough experience to levelup.  You then manually perform the levelup.   However, in some games you automatically levelup when you have the requisite experience.  

Which do we want to do?  I am personally indifferent as both ways involve equal amounts of logic for me.

One advantage of auto-levelup is that Colton won't have to add any UI element, which is good.  Thoughts?  @Jzar, @basepi , @jabelch

**Comment by basepi** [comment]
If we do auto-levelup, it should only be when combat ends, otherwise you
might be like "wtf I was fighting here!"

Otherwise I don't care either.

## 

Colton Myers

**Comment by malikoth** [comment]
Auto-levelup post combat.

**Comment by BlackVegetable** [comment]
Alright, I'll implement auto-levelup.  It'll simplify some code and make some a little tougher, but I'll handle it.  I'm changing the tag here to feature, instead of question.

**Comment by jabelch** [comment]
I agree.

**Comment by BlackVegetable** [comment]
Done.
