### ISSUE TITLE
Minutia -- How to break ties

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#18]
For the moment, assume you have no issue with the way these mechanics are handled and just answer the specific question. 

With several mechanics (magic resist vs. spellpower, accuracy vs. dodge, poison rating vs. poison, hidden rating vs. awareness, trap evade vs. trap rating) there is a roll performed by two competing stats.  When one roll outperforms the other, a specific outcome either happens or doesn't as a result.  However, the situation where the two stats tie has left me making mostly arbitrary decisions on a case by case basis.  I think we will have fewer bugs if we settle on either always siding with the _inaction_ or always siding with the _action_ in every case of a tie.

For an example of what I am talking about, review the https://github.com/basepi/akintu/wiki/Awareness page.  In this instance, action would be discovering the hidden object and inaction would be not discovering the hidden object.

What do you think?  Which should it be?  Even if you don't care, it may be important for you to know this convention when we get to programming these rules.

@basepi , @jabelch , @Jzar

**Comment by basepi** [comment]
We just roll again in the case of a tie, as discussed in our meeting.  Agreed?

**Comment by basepi** [comment]
(the roll would just be a 50/50 roll, not with the original odds, I think.  or we could use the initial odds, I don't care (and since it's an edge case the user won't notice a difference either))

**Comment by BlackVegetable** [comment]
I think you are totally correct.  Let's do that.

**Comment by malikoth** [comment]
50/50 re-roll then.  Closing
