### ISSUE TITLE
Status Effect details

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#180]
It is difficult to determine what a status effect does.  A game manual (or wiki section) detailing all of them is one non-optimal way to explain them, but there should probably be something in-game that does so.

I don't think it would be easy to display this graphically.  Do you think it would be appropriate to have a button to give information on all status effects afflicting a targeted monster in the text area?  I'm leaning toward the front-slash button as the period is being used for strengths/weaknesses of a selected monster in a similar fashion.  This will require a significant amount of work on my end, but I think it is necessary to be done before release.

I have two questions that I need answered.  1. Can you think of a better way to accomplish this?  2. How high of a priority should this be?  @basepi @Jzar @jabelch

**Comment by basepi** [comment]
Hrm, that's definitely a tough one.  But off the top of my head, I can't
think of a better way.

## 

Colton Myers

**Comment by malikoth** [comment]
The best way to do this I can think of would be a help menu.  I am imagining basically taking the existing ability selection UI, and filling it with icons representing submenus.  "Statuses", "Abilities", "Weapons", etc.  Then under statuses, have each of the statuses listed.  Have a description of the status where the ability selection UI currently has a description and the stats for each ability.  Then just have the user press "?" (or "/" if you really hate the shift key...) to open the help menu.

**Comment by basepi** [comment]
That could definitely work as well, and we have the UI for it.

Only problem is that we only have like 9 lines of description available at
the current font size.

## 

Colton Myers

**Comment by BlackVegetable** [comment]
If you cycle through each status, 9 lines is way more than enough for each.  Or am I missing something?

**Comment by basepi** [comment]
Oh, I thought @Jzar was saying we should have a single icon for all
statuses.  But with the ability to show up to 48 icons, we should have
plenty for all the things we want to show help on.

## 

Colton Myers

**Comment by BlackVegetable** [comment]
Oh, we will need more icons, there'll have to be a button to display the next page of statuses...

**Comment by basepi** [comment]
Haha, how many statuses do we have?  (Also, good idea.)

## 

Colton Myers

**Comment by BlackVegetable** [comment]
Because we are using the images for that ability that applied them and not internally what they do, we will have multiple statuses that just decrease dodge by some amount (as an example.)  I would say we have maybe 70 statuses to put up right now.

**Comment by basepi** [comment]
Gotcha.  At least it will fit on two help screens.

We might want to make it more tiered -- first help screen has buttons for
the sections, like @Jzar mentioned.  So one button for statuses, another
for something else, etc.  Unless status effects are the only thing we want
to put in the "help"

## 

Colton Myers

**Comment by malikoth** [comment]
I was implying that we'd have a nested menu.  The first one would simply help you find the group of icons to show.  The details lines would indeed only show the details for one status at a time, once you've selected the "Statuses" help item, and it switches to show you all the statuses as icons with descriptions.

**Comment by BlackVegetable** [comment]
I'm not sure I understand.  Can you try to explain what you mean by the "first one" menu?

**Comment by malikoth** [comment]
Hmmm.  I'll try again.  You hit "?", it shows a screen with icons.  There are only say, four icons.  The description for the four items are "Statuses", "Abilities", "Weapons", and "Armor", respectively.  This is the "first one" screen.  When you select "Statuses" and hit space bar (or whatever is the select button), it switches to a screen with 48 icons on it, since it can't actually show all 70 statuses.  This is the nested menu, or second screen.  If you hit a key we could define as the back button, then you go back to the "first" screen.

**Comment by BlackVegetable** [comment]
What would we show in the other sub-menus?  I mean, the abilities section could be part of the character sheet stuff but I'm not sure about the other two.

**Comment by malikoth** [comment]
I'm not suggesting having every possible creatable weapon listed or anything, just something to help the players understand the mechanical differences between weapons so they can make an informed decision between an axe they've been using and a new sword they just found.  Basically, dump the details specific to each type of item from the following pages:

https://github.com/basepi/akintu/wiki/Weapon-List
https://github.com/basepi/akintu/wiki/Ranged-Combat
https://github.com/basepi/akintu/wiki/Armor-Properties
(And make sure to include AG values from https://github.com/basepi/akintu/wiki/Armor-tolerance)
https://github.com/basepi/akintu/wiki/Attributes (Add a 5th category called Attributes to explain what they all do)

I know these aren't all up to date, with the public wiki repo.  But you can substitute the appropriate pages, right?

**Comment by BlackVegetable** [comment]
Yeah that could work.  I just don't have icons for the items.

**Comment by basepi** [comment]
Meh, if we just used a generic sword or something, life would go on.  It's
just the help screen, and the choices have names shown.

## 

Colton Myers

**Comment by jabelch** [comment]
So just weighing in on this, it would be great to have a generic status effect screen as well as one specific to the ones that currently plague your team.  The first would be linked directly in the help section.  I have no idea about the second.  I really hate mapping keys like we've done... but with no mouse support or custom mapping capability there's really not another option.

**Comment by BlackVegetable** [comment]
I think part of a help screen can be "current statuses".  I'll just display the statuses currently in play.  I'll probably implement a "next" button as well as an "up one level" button, although it would be nice to display which buttons are used for what within a help menu so you don't have to look on a wiki to know how to navigate a help menu.

**Comment by BlackVegetable** [comment]
Status details have been written up, but still need to be included in a help menu... regardless, it doesn't belong in this issue.
