### ISSUE TITLE
Shops

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#185]
Getting some kind of shops figured out would be nice.  I'm assigning this to jabelch for now, but really I'll play at least 50% of the role in this.  We need to get together (probably with @Jzar) to discuss how these are going to be implemented.  Colton's part in this is already done.  

For my part I'll implement the UI navigation and the buying/selling logic.  We need to figure out where to put the shops, what (if any) NPC icons will be used to represent them, and what to stock the shops with.  

I'm putting this in the critical-post beta milestone as a lot of gameplay revolves around getting items and being able to sell them.  I cannot do much game balance regarding items without this mechanic in place.

**Comment by BlackVegetable** [comment]
I'll just have a button that checks if you are on pane 0,0 and then opens up a shop for now.  Will you be able to work with me on saving the state of the shop to the world file?

**Comment by jabelch** [comment]
Shouldn't be too hard to work out as long as there is a form of dehydration/re-hydration in place.  It would be beneficial on my end to meet up sometime.

**Comment by BlackVegetable** [comment]
Use F2 to see how the shop works.

My end of how shops is complete beyond minor changes such as keeping the shop from changing its contents from use to use.  It could be player specific (each player has its own shop items available at a given shop.)  For now it is not saved with the world, or saved at all.  

Shops have a level that can be assigned to them.  The level determines the overall quality of the items given.  I can also implement a string that will determine what _kind_ of shop it should be.  That won't be hard.  You'll need to let me know what you're going to be doing with shops on your end now.  (How are they accessed? Where will the be accessible? Will we have different kinds of shops in different towns?  How will you determine the level of the shops?)

**Comment by BlackVegetable** [comment]
I'm also moving this out of this critical milestone, but this should be finished soon.

**Comment by jabelch** [comment]
like we talked about in irc, I would like to have a shop building in town that we enter.  From there we can access shops

**Comment by BlackVegetable** [comment]
If you write a boolean check somewhere that will tell me whether a given location is within a shop, I will make the appropriate change.  Do that first, but if you decide it is a priority, you could modify that check to return the type of shop it is (and None if not a shop at all) and I can set up different kinds of shops that way.

Examples being a shop that sells consumables, a shop that sells armors, a shop that sells weapons, a "shop" that only sells gamble equipment, a shop that sells jewlery, a shop that sells only a few items but they are very powerful/expensive relative to the other shops etc.  Most of those would be amazingly easy for me to implement.  This could be a nice way to make your Towns interesting, especially if not all towns carry the same kinds of shops!

**Comment by malikoth** [comment]
Oh, I love that Devin!  I mean, that's pretty standard for RPGs, but I didn't think we'd be able to afford to make individual shops like that.  For the record, I think the F2 should be done away with, and only open shops when you run up and talk to the shopkeeper.  But I don't feel that strongly about that thing.

**Comment by BlackVegetable** [comment]
F2 was just a hack to begin with, I'd be happy to change it!  F1 for help menus is a great idea though (Josh's idea.)  F1, ? and from the save/quit menu are good ways to access that.  But I digress.

If Josh wants to prioritize this, it wouldn't take much more than an hour for me to set up different shop types.

**Comment by jabelch** [comment]
I haven't removed F2 to open shops, but they now open automatically when you "enter" a building on the town pane.  Every building is a shop.  Feel free to close this if removing F2 is sufficient.

**Comment by BlackVegetable** [comment]
How are the opening automatically?  I need to make sure my shop caching code is still operational.  We can talk about this when we meet today.  If its being called appropriately, I will remove the F2 use and the mention of it in the help pages.
