### ISSUE TITLE
Display Gold

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#186]
We need to be able to display Current gold in the inventory and the shop screens.  Can this be passed in as an optional parameter?  Expect gold values between 0 and 99,999,999 (just to be safe.  I don't anticipate anyone at level 5 ever having over 100,000 gold at the most.)

**Comment by basepi** [comment]
## No prob. I figure I'll bump down the font size on capacity, put gold below it. 

Colton Myers

**Comment by BlackVegetable** [comment]
If you think the current way gold is being displayed is fine, feel free to ignore this issue.

**Comment by basepi** [comment]
How is gold being displayed currently?  I thought I was going to display it
in the inventory?

## 

Colton Myers

**Comment by BlackVegetable** [comment]
Doh!  I am displaying it in shops but it should be in the inventory as well (which will then transfer over to shops nicely.)  Ignore my earlier comment.
