### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#19]
@Jzar and @BlackVegetable, could you please set avatars on your Github profiles?  Makes it super easy to see at a glance who's saying what.

Thanks!

**Comment by basepi** [comment]
These avatars need not be of you.  Just _something_ -- right now it's super easy to spot when Josh says something, but your guys' comments blend together.  =)

**Comment by malikoth** [comment]
OK, I seriously had to go create another account to update my avatar on Github?  I might feel it were worth it if I could name even one other website that uses Gravatar...

**Comment by BlackVegetable** [comment]
Alright, done.

**Comment by basepi** [comment]
DISQUS.  DISQUS uses it.  I win.
