### ISSUE TITLE
Pivoting

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#193]
Monsters and players need to face targets they attack or use abilities on after using any ability.  Not having this leads to a bevy of problems, among which is that monsters detecting players behind them in stealth will continue to have their back facing those players, leading to repeated back-attacks.  

I (Devin) will assist with pivoting by making the necessary pivot call in the monster and player code, but I'll need the server-command side done by Jzar.

**Comment by malikoth** [comment]
Done.  There is no "Pivot" call, just use Command("PERSON", "MOVE", ...) and pass in a location that's a person's current location, but with a different direction property.  The server should now identify that as being a valid movement for the person who's already there, and then broadcast it.

**Comment by BlackVegetable** [comment]
This isn't working when a monster is asked to do it.  I suspect it is within the server code that is invalidating the movement.

**Comment by BlackVegetable** [comment]
Actually, maybe not.  Let me look into this myself.  I think it is on my end after all.

**Comment by BlackVegetable** [comment]
Fixed; and yes, it was my fault.
