### ISSUE TITLE
Knockback without Wrap-Around

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#198]
I need a knockback method that will allow me to move a monster's position in a given direction until it is moved back a given amount or encounters an obstacle.  The trouble with existing methods is that monsters are knocked back across edges of the combat pane, which causes bizarre wrap-around to the other edge of the pane.  I need a method that will allow me to avoid such, or some other aid preventing all forms of wrap-around.

(Notably this is not in the "Critical post-beta" milestone.)

**Comment by malikoth** [comment]
Untested but completed.  Let me know when you find bugs with the method I wrote!  =)
