### ISSUE TITLE
Review Cursed Item Proposals

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#2]
Kyle has suggested a method of handling cursed items that I approve of.  Colton and Josh need to "ok" it.\
@jabelch

**Comment by basepi** [comment]
Done.  I'm fine with the proposed method.

Note that if you don't actually move the question to the issue, let's put a link to the page in the wiki:

https://github.com/basepi/akintu/wiki/Cursed-Items

This one's a test (seeing if I can just use wiki links):

[[Cursed Items]]

**Comment by BlackVegetable** [comment]
Sorry, we should have Josh on board too.

**Comment by jabelch** [comment]
sorry about holding you up.  Yes, that sounds fine to me.  I like the idea of it wearing off after a little while.  I can see where some games wouldn't use a timer for various objects since that would get complex for the time, but that shouldn't be a problem for us.
