### ISSUE TITLE
Shields

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#20]
Quick overview before I ask the question:

Options for player combat (melee):

Dual Wielding: +Damage for lower STR characters, +On hit effects
Two-Handers: +Damage for high STR characters
One-Hand/Shield: -Damage, +Defenses
One-Hand/Nothing: Rare, some classes gain bonuses

Now, regarding shields.  I've liked the system where there are only two classes of shields: Standard and Heavy shields.  Heavy shields will be considered heavy armor for determining any AP penalty.  What of Standard shields?  Medium, or Light armor?  Or would you like to have Light Shields (bucklers?) as well?

@basepi @Jzar

**Comment by malikoth** [comment]
Hmmm, don't care.

On the topic of shields though, I once read an idea on the WoW forums I thought would be both hilarious and insanely awesome: Dual-wielding shields.  Basically your damage would be all bludgeoning and bashing, but you'd have a huge bonus to defense.  And you could maybe still throw your shields (hello Captain America) for ranged damage.  If you can work that in anywhere, that would be cool.  But it's just a wild idea.

**Comment by BlackVegetable** [comment]
Unless Colton is opposed to this, I think that should be an option for the Weapon Master.  You damage will be reduced, but will deal bludgeoning damage proportional to the internal points the shield is worth.  (That is, the points we use to generate an item that says how good the randomly generated stats are.)  Also, it will only be doable with heavy shields, as attacking with something strapped to your wrist is just silly.

**Comment by basepi** [comment]
I'm down.
