### ISSUE TITLE
Display Shop Discount

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#200]
In shops, it would be nice to be able to display the shop discount (a percent value based on cunning and gear) at the bottom of the middle pane.  Could this be an optional parameter you could display?  It should read: Shop Discount: XX% . Valid values will range from 0% to 40% I believe.  (There is a hard cap at 40% or something like it, so you only need to deal with one or two digits and a percent sign.)

**Comment by basepi** [comment]
Definitely doable.

## 

Colton Myers
