### ISSUE TITLE
Storing Sold Items

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#201]
Should we have the shops keep track of which items they have purchased from players for the purpose of players buying gear back at a later point?  Or should items sold to shops be gone forever?  I'm in favor of the latter as it will simplify my work and I don't think there is much to be gained.

Let me know your opinions on this though. @Jzar @jabelch @basepi

**Comment by malikoth** [comment]
Gone forever.

**Comment by basepi** [comment]
Gone forever, indeed!

## 

Colton Myers

**Comment by BlackVegetable** [comment]
Majority vote decided even w\o jabelch.
