### ISSUE TITLE
Message for concurrent purchase

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#202]
I plan on having the stock of a store tied to the world, not the player(s).  Thus, two players visiting the same shop at the same time could have a concurrency issue.  If both players are viewing the shop at the same time and both see a Greatsword for sale, if player A buys the sword and then player B attempts to buy the sword, it will need to display a message (and update the shop-view) to indicate that the item is no longer available.  

What message would be appropriate to be displayed in this circumstance? I am thinking either "Someone just bought that, sorry!" or "Out of stock."  Any ideas?  @Jzar @basepi @jabelch

**Comment by basepi** [comment]
Personally I've always preferred shops without stock issues.  (Think Final
Fantasy)  But in the end, I don't care much either way.  And "Out of Stock"
is fine -- "Hey, did you just buy that greatsword?!?"  "Ya, sorry mate"

## 

Colton Myers

**Comment by BlackVegetable** [comment]
Well there is that possibility.  What do you guys think about unlimited stock options?  (hehe)

**Comment by jabelch** [comment]
I like the idea of enough stock for everyone, kind of like chests.  If you're both in the shop when it was there, you both have the option to buy it.

**Comment by BlackVegetable** [comment]
Resolved.
