### ISSUE TITLE
Change the display value of items, if specified.

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#204]
When I pass in two lists of items, I want to be able to pass in a duple of floats that indicate how much to multiply the "value" s of the items by for display purposes.  The left number in this optional duple will affect the left list, the right the right.

**Comment by basepi** [comment]
Note that this will cast the result to an `int`, and so will always round down.

**Comment by BlackVegetable** [comment]
Excellent, as that is what I am doing anyway.
