### ISSUE TITLE
Finish Hardcore deletion

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#208]
The saved games need to be deleted on hardcore death.  I'm assigning this to Kyle, but I think @jabelch may need to be involved instead.

**Comment by malikoth** [comment]
lol  So, why did you assign it to me then?  Reassigning.

**Comment by BlackVegetable** [comment]
Because I thought you would know who needed to be involved.

**Comment by jabelch** [comment]
Devin, is there a way to reset a player's object to the default (as if TheoryCraft was creating it from scratch)? That would be helpful so we can allow them to continue playing, but as a new character.  I keep running into bugs when I try and replace them with a new character.
See servercombat.py line 511 (hardcoreDeath())

**Comment by BlackVegetable** [comment]
Yeah, I can do that.  I'll write a method to do so.  I'll need to do something similar to handle respeccing anyway.

**Comment by BlackVegetable** [comment]
@jabelch  What bugs are you encountering when you try to replace a character with a new, level 1 version of that character?  It should be the same call as when a new character is created on a completely fresh game.
