### ISSUE TITLE
Summons

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#21]
What do you think about the complexity of adding summonable allies (via magic) that last a few turns?  They could be either player controlled or AI controlled.  It is a feasibility issue that I wonder about.

@basepi @Jzar

**Comment by malikoth** [comment]
That could be the purview of the Sorcerer.  I don't think it'd really be too hard, but idk.  I haven't taken an AI class

**Comment by BlackVegetable** [comment]
Many of the summons would be pretty dumb, and intentionally so.  A magically enchanted (summoned) flying sword doesn't have to have the best AI ever...

Regardless, we're going to be learning more about AI than we may have ever wanted to just for the monsters in the first place.  Aren't you at a LAN party?

**Comment by basepi** [comment]
WORKING AT A LAN PARTY FTW!  We're already doing monster AI, should be trivial to apply it to summoned allies.  So I'm down.

**Comment by BlackVegetable** [comment]
As a parting comment, I'm thinking we'll develop the hybrid classes first and only include the last 4 doubled classes if we really have time.

**Comment by basepi** [comment]
Should be trivial to add.  As long as we program this in a sane manner.+-
