### ISSUE TITLE
In-Game help/tutorial

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#210]
And in-game help interface needs to be designed.  I think Colton has the first responsibility as he has to code up the actual images.  I will probably do the majority (all?) of the logic and text.  This needs to be robust enough that players could figure out all but the behind-the-scenes mechanics of this game without going to the wiki.

Colton should assign this to me once he is finished on his end.

**Comment by basepi** [comment]
I was under the impression we were going to use the ability selection screen for this?

**Comment by BlackVegetable** [comment]
I just need to know if you are planning anything differently.  If this is all that we need/want, you can go ahead and assign it to me, although that means it is time to decide exactly what we want in there.

**Comment by basepi** [comment]
I'd be happy to modify the ability screen in any way we need in order to
make your job easier -- but I think it's a pretty good base upon which to
build the help menus.  We just need to find a couple of generic,
subject-specific icons for things we don't have icons for.  I'd also be
happy to help find a couple of these (we don't need many, we can mostly
repeat them because we have names under the icons), but not until Thursday.
 =P

## 

Colton Myers

**Comment by BlackVegetable** [comment]
Right; I will handle getting the icons (and coloring them and resizing them if necessary.)  If the rest of you can aid me by letting me know what things we will need represented, that would help.

**Comment by BlackVegetable** [comment]
@Jzar, @jabelch, @basepi 

What are the categories that will need to be represented in this?  Please help me brainstorm what we'll need to include.  Also, details on monsters and details on current status effects in play should have a way of being displayed in combat via help menu.  Should we have a separate kind of help menu for in-combat that will make it easy to display such?  Please give me your thoughts on those two questions.

**Comment by basepi** [comment]
Could we add those in-combat help topics dynamically if the user is in combat? Dunno what that would require logic-wise. 

## As far as categories, we need keybindings, statuses... I'll think on others. 

Colton Myers

**Comment by BlackVegetable** [comment]
Yes, that was my plan.  It shouldn't be hard to set up the logic for such.  Please do think on a full list of topics (for both dynamically generated things for combat as well as static/comprehensive things for the overworld.)

**Comment by BlackVegetable** [comment]
This is done.  But I will probably modify it a tiny bit before our documentation deadline.
