### ISSUE TITLE
Button for picklocking & bashing chests (doors?)

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#212]
What button should be used for picking a lock on a chest?  Should the same button be used for bashing a chest open? (The first attempt would be an attempt to pick the lock; the following attempts would be to bash it open.  You can either pick the lock or you can't, there's no roll involved.  Bashing does involve a random roll.)

Any ideas? @Jzar, @jabelch , @basepi

**Comment by basepi** [comment]
Does picking a lock require any sort of resource?  (Consumable lockpicks,
for example)  If not, then I'd say same key, pick first then bash.

## 

Colton Myers

**Comment by malikoth** [comment]
I vote same key.

**Comment by BlackVegetable** [comment]
G will picklock as well as open.  B will bash as that decision needs to be made with wisdom; a team of players shouldn't accidentally have the barbarian break down a chest accidentally while an Assassin could have unlocked it.
