### ISSUE TITLE
Change gear in combat

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#217]
For simplicity's sake this should probably be limited to just weapons (including shields as well) rather than any piece of gear you'd like.  

Would that be an issue for anyone?

Also, should we implement a dedicated weapon to switch to (like in D2 or TL2?)  Or should you be able to switch to any other weapon?  I could do either pretty easily.

Thoughts on either question?  @basepi @jabelch @Jzar

**Comment by basepi** [comment]
No thoughts, don't care either way.

## 

Colton Myers

**Comment by malikoth** [comment]
My thoughts during design phase had been to have a two dedicated weapon sets, a la TL2.  So that's my vote, don't much care anymore, though.

**Comment by BlackVegetable** [comment]
We will need some way to indicate which weapon is equipped as an alternate then.  Thoughts?

**Comment by BlackVegetable** [comment]
Additionally, what button should we reserve for such a switching operation in combat?

**Comment by basepi** [comment]
That button that we're not using for something else already.  You know the
one I'm talking about!  ;)

## 

Colton Myers

**Comment by BlackVegetable** [comment]
Oh! you mean Scroll Lock?

**Comment by basepi** [comment]
...

## 

Colton Myers

**Comment by malikoth** [comment]
Ctrl+Alt+Del

**Comment by basepi** [comment]
Fine with me!  Doesn't do anything on OSX

## 

Colton Myers

**Comment by malikoth** [comment]
Yeah, cuz you don't have a Ctrl button...

**Comment by basepi** [comment]
Hey Jzar, your ignorance is showing!
http://www.userinter.net/wp-content/uploads/2011/05/Mac-OS-X-Keyboard.jpg

;-)

## 

Colton Myers

**Comment by BlackVegetable** [comment]
@basepi I'm going to need some way to indicate weapon sets in the equipment/inventory view.  Different colors for main set and alternate set would work.  We need to work together to make this happen because there needs to be a UI cue that a weapon set is your alternate as opposed to your current set.  Sadly, this can't just be one item, it can be a single two-handed weapon, a single one-handed weapon, a weapon and shield, or two one-handed weapons.  Lame, I know.

**Comment by basepi** [comment]
## Kk. Can you create a separate issue, assign me, put it under graphics engine, etc. 

Colton Myers

**Comment by BlackVegetable** [comment]
This has been finished but ought to be tested more when it comes to equipping two weapons or a weapon and shield in the alternate set.
