### ISSUE TITLE
MOAR trap images

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#218]
I'm going to try to use a different image for each trap. Because I'm not planning on implementing the Tactician before release, this won't be so bad.  However, I'm going to need images for the following traps:
- Sticky Trap: It should look like something sticky.  It slows down enemies but deals no damage.
- Boulder Pit Trap: It should probably just look like a pit, but if you can think of something else, go for it
- Explosive Trap: It should just look like a bomb? (It explodes on enemies in an AoE)
- Beacon Trap: It lights up targets, making them easier to see\hit with ranged attacks and slightly lowers magic resist.  I'm not sure what you think this should look like.  Perhaps a big button on the ground?

I will resize these images to 48 x 48 as needed but they should still be .png files as usual.  Because you can lay down traps and replace previous traps, this is somewhat important.  Another reason this is important is because traps like a shrapnel trap (which deals damage) and a sticky trap have very different functions, tactically.  A caster might want to hide behind some sticky traps to ensure enemies cannot reach them in a single turn, but someone else might lure an enemy into a few shrapnel traps to finish them off.  

Also, if you find extra trap images while you're at it, I could use those for hostile traps.

Thank you.

**Comment by jabelch** [comment]
Done and implemented:
Only thing, traps.py doesn't have explosive or beacon traps implemented (at least I didn't see them), do you want me to do that?
Any other thoughts on the other traps you want, ideas of what they might do so I can search accordingly?

**Comment by BlackVegetable** [comment]
Those traps aren't ready yet as I haven't finished the classes that use them.  Thank you though.

**Comment by BlackVegetable** [comment]
Each of the "monster traps" in trap.py could use an image.  Alternatively we could use the same image for all such monster traps.  The names should make it pretty clear what they do.

**Comment by BlackVegetable** [comment]
Traps currently in game (hostile):
'Bear Trap'
 'Standard Dart Trap':
'Fire Trap':
 'Ice Trap' :
 'Lightning Trap' :
'Mana Siphon Trap'

**Comment by jabelch** [comment]
Just used the current bear trap for the 'Bear Trap'
Otherwise, take a look and see if these are acceptable.
