### ISSUE TITLE
baseHP not accurately reflected by the GUI

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#219]
When we adjust the monster's HP based on the number of players in the pane, the GUI doesn't actually reflect the correct amount.  I did an explicit print statement in pane.py line 518 (in CombatPane.place_monsters)

Loading pane ((0, -1), (6, 8), 8)
Monster baseHP: 71.0
Monster baseHP: 24.0
Monster baseHP: 24.0

But the GUI reflects:
47
16
16

**Comment by BlackVegetable** [comment]
Fixed.
