### ISSUE TITLE
Rework Location-targeting abilities/spells?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#220]
As it stands there is no real system set up for targeting a location with an ability.  Traps are using the numpad to place themselves, which is not great as it makes it impossible for players without numpads to play Ranger-primary classes.  

Not only would it be nice to have some way to select tiles for traps via a cursor, it is necessary for a number of spells and abilities.  Now, I can rework those abilities to function differently (they are always centered on the caster, or rework them entirely into something else) but if any of you think we can/should create a location-based targeting system in the next few days let me know.  

Would anyone be able to create a cursor-based selection system?  Or should I punt on trap-placement for people w\o numpads and rework all location-based abilities?  I need to know sooner than later.

@Jzar, @jabelch , @basepi

**Comment by basepi** [comment]
Remind me why it needs a numpad?  You could go back to the diagonal controls for moria (BNYU or something like that) to get the majority of the numpad.

Cursor-based selection system would be good, though, and the GUI is in place, just need to use an overlay for your cursor.

**Comment by BlackVegetable** [comment]
We could use something else but not anything that touches N as it would be too easy to end your turn accidentally.  I'm not going to be the one that implements cursor selection.  If that _is_ going to be done, it needs to be done in the next couple of days.  Otherwise, I'm giving up on location targeted abilities and replacing them with other, lamer abilities that I actually have the capacity to implement.

**Comment by malikoth** [comment]
I'll do it.  I'm going to get a huge swath of work done tomorrow.  I still have to finish up my issues from Critical Post-Beta, and I'll try and stick this in with them.  I think all that'll be a fair day's work.

**Comment by BlackVegetable** [comment]
Dude, if you get this, it will save me many hours of work reworking things.  I appreciate that.

**Comment by malikoth** [comment]
Finally, done.  I believe  ;)
