### ISSUE TITLE
Combat Pane levels

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#221]
I need a way to know the level of the combat pane.  That is, how difficult the traps should be (and the monsters already are.)  Would this be an easy thing to add to a combat pane such that I can access it?

Thanks!

**Comment by jabelch** [comment]
How is this different from the level of the monster?  Do you want some metric that looks at the monsters and determines the level based on their total HP?  That can be done as well as looking at the distance from a Town... what do you have in mind?
