### ISSUE TITLE
Server RUN character flashing

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#224]
When running, if you press a different direction, you will sometimes get an artifact where your character flashes in the next position, but stops in the current one.  

Try different directions, since it doesn't always happen.

**Comment by malikoth** [comment]
This will be fixed when I get around to fixing issue #135.  I'm going to leave it open however, just in case I never do get around to completely reimplementing that, as fixing this one issue by itself should still be feasible once I dig down and understand what's causing it.

**Comment by malikoth** [comment]
I believe this is completely fixed.
