### ISSUE TITLE
Refactoring Inventory Stuff

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#227]
Devin,

I didn't get to redoing the keybinding stuff (which includes the aoe cursor selection thing I'm going to do, they're fairly related) today.  But I did start looking at it, and I realized that I cannot do this on my own.  I need to work with you for a lot of it.  Mainly because logic controlling the interface has left game.py.  I need to have everything that deals with keypresses moved back into game.py (all of playercharacter.navigateInventory)

I am sorry that I wasn't available to help implement all this keyboard stuff in the first place, and you did a good job making it work, work well, and work correctly.  However, I disagree with some of the architectural decisions and I believe we need to reverse them for me to proceed with fixing the mess of keybindings, and from there, implement an elegant aoe targeting cursor.

Can / will you help?

**Comment by BlackVegetable** [comment]
Yes, I can help.  The move to playercharacter.py wasn't great, I agree.  However, levelup.py and shop.py have been pretty handy.  Still, we can discuss this.

**Comment by malikoth** [comment]
Oh dear, I didn't realize there was more interface handling in levelup and shop...

**Comment by BlackVegetable** [comment]
It might not be as hard to deal with there as you'd think.  It is designed to be more modular such that if you send it an input key of some custom type that you build (such as SELECT instead of the literal key value from pygame's key class, it should be easy to switch to.)

**Comment by malikoth** [comment]
Good work on this by the way, and thank you for your help, Devin.
