### ISSUE TITLE
Fix combat MonsterPhase

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#236]
I was stupid when designing combat, and suggested we just make monster movement more or less instant.  I forgot that like players, they can do more than one action per turn, and so all of their commands are issued simultaneously, and the animation skips all of them except the last.  It is visually disconcerting and needs to be fixed.

**Comment by malikoth** [comment]
What the heck?  I did NOT close this...

**Comment by BlackVegetable** [comment]
Pathfinding needs to be fixed for this to really be optimized.  It is likely very close to functional, but pathfinding needs to be working for it to be tested.

**Comment by malikoth** [comment]
I believe pathfinding is working now.  Back to you Devin!

**Comment by BlackVegetable** [comment]
And now we go to pathfinding for ranged monsters, back to you!

**Comment by malikoth** [comment]
OK, I believe I've got this working perfectly now.  I even found another place to test it, and seems fine to me, though I can't seem to survive long enough to tell you if they're actually casting / attacking from their next-best positions.  I think I'll reassign it to you one last time, and unless you have anything else to do or request on this, please just close it.
