### ISSUE TITLE
Base Character class abilities (3)

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#24]
Must be completed up to level 3.

**Comment by basepi** [comment]
Whoops.  Assumed everything was still questions, so I just lumped it in there.  Definitely an enhancement.  =)

**Comment by BlackVegetable** [comment]
Yeah, I'm playing with milestones.

**Comment by basepi** [comment]
That's fine, I just didn't read.  =P

**Comment by BlackVegetable** [comment]
Fighter Abilities finished to level 3.  (1/4 Complete)

**Comment by BlackVegetable** [comment]
Wizard Abilities finished to level 3. (2/4 Complete)

**Comment by BlackVegetable** [comment]
Thief Abilities finished to level 3. (3/4 Complete)

**Comment by BlackVegetable** [comment]
Done with all four.
