### ISSUE TITLE
Keybinding Dialog

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#248]
Should basically be a copy of the shop or inventory dialog.  I will populate the three panes with keybinding specific text, and handle all input and functionality.  If you can just show me the method calls to create the dialog, move the cursor, and query the cursor's current position, I should be able to do the rest.

Thank you!   ^_^

**Comment by basepi** [comment]
This is done and pushed.  I can run you through the API any time, @Jzar.  (I expect we will in about 10 minutes here)
