### ISSUE TITLE
Kyle's "post this in a gist" print statement

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#271]
Posted a gist here: https://gist.github.com/jabelch/8ca34718ae86e7d274a9
You can replicate this error every time by going into combat with the vile apprentice on pane (2, 0) using the backdoor.  Couldn't get it to replicate when going into combat on (1, 0) (and she immediately walks into (1, 0) so you have to be quick or patient... she does come back)

Edit:
Just got this error when monsters are at the top of the combat pane as well:
https://gist.github.com/jabelch/b7c1d6e3fd4e32cb2c87

![KeyError](https://f.cloud.github.com/assets/1383245/394837/6314357c-a7d7-11e2-927f-e88ebc960f57.png)

**Comment by jabelch** [comment]
Ok, so I think I narrowed down part of the issue.  When the monster starts on the far left tile, the path finding breaks.  I've pushed a _mask_ fix by preventing a monster from starting on x=0.  You can remove that fix by looking at line 616 in pane.py and removing the last check of my while loop (... or loc.tile[0] == 0:).  That will allow you to replicate this issue if you are interested.  It also causes issues with the y=0 location, but I haven't put in code to mask that issue.
I don't know if it causes problems when monsters are on the far right or bottom tiles of the pane either.

**Comment by BlackVegetable** [comment]
I found a possibly related one of these.  I'll post the stacktrace here:

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ python akintu.py
1337 None {'seed': 'Correct Horse Battery Staple'} ('Mysterious Adventurer', 'Hu
man', 'Nightblade')
Listening for clients...
Connecting to server...
Connection made with client on port #4015
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Loading pane (0, -1)

# Loading pane ((0, -1), (19, 19), 0, 8)

SELF: ((0, 0), (13, 19), 0, 2), DEST: ((0, 1), (13, 2), 0, 2)
13, 13, 22, 22

# PLEASE POST THIS AS A GIST AND GIVE IT TO KYLE, THANKS

# 

SELF: ((0, 0), (13, 19), 0, 2), DEST: ((0, 1), (13, 2), 0, 2)
13, 13, 22, 22

# PLEASE POST THIS AS A GIST AND GIVE IT TO KYLE, THANKS

Server error: Attempted to stop non-existent ai function: run
Server error: Attempted to stop non-existent ai function: run
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 169, in ga
me_loop
    self.check_queue()
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 217, in ch
eck_queue
    self.currentAbility = self.pane.person[self.id].abilities[0]
exceptions.AttributeError: 'Monster' object has no attribute 'abilities'
