### ISSUE TITLE
Trapped monsters!

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#272]
Check this out.
![image](https://f.cloud.github.com/assets/2665839/405489/a732ab28-a9e2-11e2-8d39-518cc8801049.png)

**Comment by BlackVegetable** [comment]
I'm glad I was a ranged class!

**Comment by jabelch** [comment]
Fixed monster placement to ensure a path to the outer edge (namely (0,0))

**Comment by BlackVegetable** [comment]
Not bad!
