### ISSUE TITLE
Game freeze on combat pane generation?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#273]
![image](https://f.cloud.github.com/assets/2665839/410214/e2001480-ab67-11e2-93af-4c8d4f1a1663.png)

**Comment by BlackVegetable** [comment]
Notice that he's between moves.  I had just pressed UP.

**Comment by BlackVegetable** [comment]
This happens every time on this monster in this world.  Doesn't matter whether he's in the middle of a move or if he's even on that tile.

**Comment by BlackVegetable** [comment]
I suspect it might be limited to just that stamp for some reason.

**Comment by jabelch** [comment]
Fixed
