### ISSUE TITLE
Review Soft Level Cap Rebuttal

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#3]
Kyle convinced me that a soft cap may be totally unnecessary.  Just include a difficult to reach hard cap.  Perhaps we'll consider higher levels in the event that we have extra time and feel it is needed.

Agree?

@basepi , @jabelch

**Comment by basepi** [comment]
That sounds fine to me.  =)

**Comment by jabelch** [comment]
we could have a logarithmic system, you would never _quite_ max out... _so_hard_to_level...\* toward the end.

**Comment by BlackVegetable** [comment]
I think that's the idea overall, but if we're going to have neat abilities that you only learn at max level, it should be reasonable for a fraction of the playerbase to reach that maximum level.

**Comment by basepi** [comment]
Definitely should slow as you go, but not to the point where it's ridiculous.  =P

What a troll that would be.  "I'M SO CLOSE!"  (4 hours later) "EVEN CLOSER"  (24 hours later)  "$#&@ this."

**Comment by jabelch** [comment]
Agreed.  There must be an attainable maximum.  What might make it even more interesting is the combination of items as a means to gain more power after maxing out.  As your character continues to accrue more gold and encounters more exotic or expensive items, their abilities can continue to get better.

**Comment by basepi** [comment]
Sounds like we're in agreement.  If someone wants to add this conclusion to the wiki, we can close this issue.

**Comment by BlackVegetable** [comment]
I will add it.  Issue closed.
