### ISSUE TITLE
Set Items and uniques

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#35]
Do we want some kind of system for items that are not autogenerated but rather are special and have been created by us?  I am against this, but I thought it was worth asking.  If we do it I would prefer it be a tier 3.5 feature.

@Jzar @basepi

**Comment by malikoth** [comment]
I think set items should either not be implemented, or should be tier 3.5  However, unique non-random items could be fairly easy to implement and could be a lot of fun.  Don't have any specific ideas at the moment, but there could be some fun items specific to particular locations of our world, that could add more meaning to the world-generation algorithm.

**Comment by basepi** [comment]
That'll be one interesting aspect of world generation, is how much of it we generate and then randomly plop into the world, vs actually randomly generated.

**Comment by BlackVegetable** [comment]
Uniques can be figured out later, once we are working on world generation.  Set items are out for now at least.
