### ISSUE TITLE
Poison Use -- Ability or pure item?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#38]
I've had second thoughts about my view on how poison should be handled.  Originally I proposed Poison be restricted to Ranger or Thief classes (Ranger won) and have a level requirement to unlock the ability.  It also consumed (and required) one item each time it was used, but lasted an entire battle.  

However, I see that it would stand alone as the only ability to require an item.  Furthermore, it doesn't fit with our previous decisions to allow any class to use any item, but some classes may use some items better than others.  

Thus, I am thinking of making poison usable by all classes, but Rangers (and thieves?) will get a passive bonus to the damage it deals.  Do you have any thoughts?

@basepi , @Jzar ?

**Comment by malikoth** [comment]
I like the thought of making it usable by all with bonuses to classes that specialize in it.  If you make it so rangers and thiefs get that passive poison buff, then almost 3/4 of our total classes will get it.  Even if its only the ranger and thief primaries, that's still half.  We could make it just the 4 classes that are some combination of thief and ranger.  i.e., Marksman, Assassin, Druid, and Shadow.  Ninja and Tactician could conceivably be added.  But I kind of like restricting it to just those 4.

**Comment by BlackVegetable** [comment]
Shadow should get some bonus, I haven't done him yet though.  Marksman could as well, I suppose.  Druid has large poison bonuses.  Assassin is the only one I haven't added that to.  He might get some bonuses but I think they'll come later than level 3.  (Assassin is pretty cool already even without poison, in my opinion.)

**Comment by basepi** [comment]
Sounds fine to me.

**Comment by BlackVegetable** [comment]
Alright, I think we can close this issue.
