### ISSUE TITLE
Decide upon Death Penalty for Softcore Characters

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#4]
We either need town runs or gold cost (something else?) but not both.  
@jabelch , @basepi , @Jzar

**Comment by basepi** [comment]
Why not a choice, like in Torchlight?  Just a thought.  Simpler to choose one, though.  I'm thinking town runs.

**Comment by BlackVegetable** [comment]
I vote just choose one, and I'm not too set on either way.  Kyle? Josh?

**Comment by malikoth** [comment]
We're in research forum right now.  Maybe you'll hear from us later
tonight.  (Does replying to this e-mail work to add on to the issue
history?)

**Comment by basepi** [comment]
Indeed it does.

**Comment by BlackVegetable** [comment]
Yes, it does!

**Comment by jabelch** [comment]
as annoying as it is, I think a gold penalty can be good, but perhaps not sufficient. If you are in the middle of combat, removing the character is a must.

**Comment by BlackVegetable** [comment]
Right, within combat the character will be dead, but with a gold-cost only system, they'd spawn at the start of that floor which would take 20-60 seconds to get back to where they were (sans gold.)

**Comment by basepi** [comment]
We could do ~10% of their gold (like Borderlands 2).  It would hurt then (assuming we make gold useful -- I rarely use money in Borderlands 2, otherwise that death penalty would be much more of a bummer).

**Comment by jabelch** [comment]
I liked how DOTA uses gold - allowing for item customization and just as you get enough gold to make radiance you die.  It would be nice to have similar customization... but I think that goes in a different direction than this post.

**Comment by basepi** [comment]
How we make gold valuable -- definitely an issue.  If anyone played D2, you might remember gold being completely useless, and people starting to just use certain rare items for bartering.  A whole gold-free economy sprung up as a result.  We should definitely work hard to make gold valuable, in my opinion.  Of course, as usual people can cheat if they want, but we're working on the assumption no one cheats.

I will say that Borderlands 2 gold became a little more valuable once I discovered the slot machines.....I still haven't rolled 3 vault symbols, but someday I will!  =P

**Comment by BlackVegetable** [comment]
Lets have value to our gold.  I can find ways to make that happen and I'm sure your ideas will be invaluable as well.  Gold cost for death and having to spawn at the start of the region/floor you were on when you died is the softcore penalty.  Is that good?

**Comment by basepi** [comment]
Sounds fine to me.
