### ISSUE TITLE
Running from Battle

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#44]
Should players be able to run from a battle they have already engaged in?  I vote no.  My reasons:
- It would require implementing (and theorycrafting) a running away system.
- It would lessen the penalty for trying to sneak past foes and steal treasure and getting caught if they could just run away every time.
- It would probably be difficult to implement in a fun way.

Let me know if you disagree; this one is somewhat important.

@basepi, @jabelch, @Jzar

**Comment by basepi** [comment]
I'd be fine with making it not a feature.  Maybe you have to use a consumable (escape rope or such) to do so?  Or completely impossible.  Don't have strong feelings on this one, though you're right, it would be hard to implement in a fun way, methinks.

I will say this -- we probably shouldn't make any enemies that are much faster than the player in the overworld if we don't allow running from combat.

**Comment by BlackVegetable** [comment]
I agree that we shouldn't have _many_ such enemies.  If we do, they shouldn't be seen by lower level players at least.

**Comment by BlackVegetable** [comment]
Via the chat channel, some comments have been made:
- Not being able to run in Hardcore mode would present an ugly situation where you get into a battle far harder than you anticipated and lose your character.

A couple of ways to run away were presented:
- Randomly trash one piece of equipped gear in exchange for running.
- Use a consumable to run away.

I would like to propose the following system:
- Softcore = no running away, or implement the hardcore system, but running away holds little advantage that way...
- Hardcore = Successfully running away costs 10% Gold, and/or consumes an expensive consumable.  Either way, running away consumes and requires all AP for that player that turn and only has a 75% chance of success.  
- Both = Implement a feature to estimate the difficulty, or view the monsters inside of a "group" of overworld monster(s) from a distance.

I propose the 75% chance for hardcore escape to give players that accidentally entered combat (such as by failing to sneak past a foe) a very high chance to escape if they spend the turns at the start of battle attempting to escape instead of moving into range of their target.  However, it makes running away one-hit away from a poorly fought battle less of a for-sure option.

In either event, I think escaping from combat should not be a priority for our development and should be at least a tier 3 feature, if not later.

**Comment by BlackVegetable** [comment]
This is a late tier item; let's worry about it much later.
