### ISSUE TITLE
Entering Combat Together

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#45]
@basepi , @Jzar 

Apologies in advance for the Wall-O-Text.

We have a concerning issue with our combat system.  If a player enters battle with a foe while one of his buddies is close enough to increase the difficulty of the battle, he will be facing a tough foe alone.  Even if the allied player joins the battle during the second turn, that player is one turn behind in preparing buffs, performing ranged attacks, or moving into melee range.  This also presents some logistical details that need to be worked out.

We could remedy this, partly, by forcing a player adjacent to a player that engages in combat with a monster to be sucked into the same combat.  Using your NUMPAD as an example, the monster is on the 8 key.  Player A engages the monster from the 5 key, while player B is standing on the 2 key.  Player B is sucked into the battle and will start from roughly the same angle as player A.  

This could apply only when battle commences, or anytime a player tries to shuffle by a battle (and gets too close.)  We should consider the latter as we don't want one player to be able to sacrifice himself against a boss only to allow an allied player to ignore the battle and grab the treasure the boss was guarding (supposing the boss was in a narrow corridor?)

The logistics involved may require us to "pause" the battle briefly while an allied player zooms into battle partway through.  We will want the player to be able to start combat at the start of the next player turn but if he is currently loading the combat, in some cases I think the combat will need to pause until that player is loaded and able to fight.  Hopefully such delays, while common, will not take too long.

My main questions are: **"How should we handle the issue of players desiring to start (the same) battle at once?"** and **"How should we handle the (possible) delay  when a nearby player enters the combat?"**

**Comment by basepi** [comment]
I don't think it's as big of an issue as you make it sound -- I think we could pull them both in, that would be fine, but I also don't think one turn is going to make a huge difference -- the combat just won't be that balanced.  In much the same way you can solo some lower level monsters alone in Torchlight when you have two players, I think you'll be able to handle yourself OK with multiple players in Akintu as well.  It might be another thing we just workshop after we get the game going and see what works and what doesn't.
