### ISSUE TITLE
Event Based performance issue?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#49]
For many passive abilities and some buffs, I feel that unless we take an event driven approach to many actions in the combat engine, the code will become unmanageable.  

However, I worry about the performance hits of having many listeners and broadcasts going all the time.  For example, some broadcasts I would need active off of the top of my head:
- Spell cast
- Counterattackable melee weapon attack performed
- HP dropped below threshold
- Healing performed

I suppose I can optimize which listeners are active at a given time based on which passives a character has and which classes they are etc. but I wonder if the general pattern is going to still slow down the game to an unplayable level.

Any thoughts?

**Comment by basepi** [comment]
One huge drawback to using python is that it's very hard to get any sort of performance with multithreaded code.  I feel like this particular issue may be one we have to tackle once we're in the code and get a feel for things.

**Comment by BlackVegetable** [comment]
I suppose you are correct.  The pattern you described to me in class will be easy to implement from the encoding I have used.  I hope (and believe) we will be fine with single-threaded processing.
