### ISSUE TITLE
Out of Combat Stealth

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#5]
How should stealth out of combat be handled? Can rogues sneak by monsters, start combat in stealth, start combat adjacent to enemies?

Colton: If stealthed outside of combat, AI won't move towards the player unless they can detect them. Originally I was thinking that we force combat if you get adjacent to an enemy, so we can have choke points. But we can just generate locked doors with a key on the monster to force combat. If you get into combat while in stealth, you will be spawned randomly on the battlefield just like normal, except you'll be in stealth.

@jabelch

**Comment by jabelch** [comment]
I like that - for some monsters though, I envisioned running into them randomly during normal travels outside of dungeons.  If this is the case, perhaps we will have some optional fights that so long as the monster doesn't detect you, you can avoid it altogether; or use the stealth as an initial attack bonus.

**Comment by BlackVegetable** [comment]
I agree with this.  Most fights should be optional, but you'll want the experience/gear from them most of the time.  @Jzar, any thoughts?

**Comment by malikoth** [comment]
Traditional model is to be REALLY open-world.  No forced encounters, no
locked doors.  Every level deeper into the earth you descend the harder the
enemies.  It's up to you to be a sufficient level for where you are, and if
you find yourself dying too much, go back up a little bit and level some
more then try again.

Even if we have a storyline, I don't think there's a need to force
anything.  Let the user try a boss that's 2 levels higher than him if he
wants to.  It'll allow the players to control the difficulty of their
gaming experience all by themselves.  So to make a long story short, I see
no reason to force the player to get into combat.  Traditionally, you just
run around / past any monsters you REALLY don't want to fight, and then
close / lock / jam a door shut.  But if the Rogues want to stealth out of
it, more power to them.

In order for this system to work, the only thing WE have to do is ensure
that the random world generation algorithm creates enough content at each
level before presenting content of the next level.

Anyways, that's my $0.02.

**Comment by BlackVegetable** [comment]
I am in agreement with Jzar.  All fights can ultimately be optional but without stealth, some might be harder to avoid than others.  However, I would like locked doors that can be picked/bashed/opened with magic.  Bashing would require strength and would not give any exp (if such is to give exp.)  

This isn't really my area of the game development so I'm not overly emotionally invested in any decision here though.

**Comment by basepi** [comment]
Sounds fine to me.  Definitely will have to tune things for plenty of leveling content, though.  I'd rather not force grinding, though respawns+grinding is an easy solution.

However, if doors can be picked for XP, they should be able to be bashed for XP.  (Meh, I guess I don't care, just would make sense to me.)

**Comment by jabelch** [comment]
of course your bashing experience would increase with previous bashings...

**Comment by malikoth** [comment]
Bashing does grant XP in Moria too, so I support that.  And I like being
able to achieve the same effect with a spell too, as in Oblivion!

**Comment by basepi** [comment]
Wow we got a little off-topic.  We seem to have come to consensus, though, so if someone wants to add this to the wiki, we can close the issue.

**Comment by BlackVegetable** [comment]
Not entirely.  If a player enters combat from a stealthed state, does he start combat stealthed (I vote yes.)  Does he start in a backstab position if he was stealthed and behind the monster in the overworld? (I vote yes as well.)

**Comment by basepi** [comment]
I would actually vote yes, and no, respectively, but am not overly worried either way on the second question.

**Comment by BlackVegetable** [comment]
Any others about the backstab position?  I'm not too set either way, to be honest.

**Comment by malikoth** [comment]
I vote if he's stealthed out of combat, he enters combat stealthed.  And I'd always been thinking that whatever direction the player approaches combat from, that's the edge or corner of the arena he starts in.

**Comment by basepi** [comment]
But not on the square adjacent to the monster, correct?

**Comment by BlackVegetable** [comment]
Hmm, if you enter combat stealthed it might be a pain.  Stealthing makes movement cost more AP, slowing you down.  Frequently, players would then disable stealth just to reach the target.  Perhaps they can be closer, but not adjacent to, the monster to compensate when entering with stealth?

**Comment by malikoth** [comment]
I like positioning them closer to the target, but not next to them.

**Comment by basepi** [comment]
Roll what your position would normally be, then place you halfway between that rolled location and the monster?

**Comment by malikoth** [comment]
Yeah, that's what I've got in mind at least.

**Comment by BlackVegetable** [comment]
That should be fine.  Playtesting here will have to determine if that will work perfecly, but because Stealthing typically doubles the cost of movement, halving the distance sounds perfect.
