### ISSUE TITLE
Replace two abilities

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#54]
From the email I sent:

Hey, I have two abilities that I am no longer fond of.  They will require too much time/effort to implement and debug, and, frankly, they aren't very interesting.

Check the Wizard and the Thief pages to see them.

The Wizard ability that needs to be replaced is "Apply Salve" which allowed a Wizard base class character to use a potion on an ally.  The Thief abillity that I'd like to replace is "Steal Potion" which stole a potion from a monster that happened to be carrying a potion.

They are both fairly low level abilities.  If you have any ideas either conceptual or mechanical, I would greatly appreciate it.  Once I get those encoded, I won't have to do any more data-entry for the abilities.

@basepi @jabelch @Jzar

**Comment by jabelch** [comment]
For the Thief, how about just steal - it would attempt to take something low level from the monster.  If anything, the monster wouldn't even have to maintain an inventory, just generate an item randomly.  The higher the skill, the more useful the item.

**Comment by BlackVegetable** [comment]
I was trying to avoid being able to acquire items from monsters that the wouldn't drop upon death due to the strangeness of the concept in general.  That was why I thought stealing a potion would be something useful as it would deny the monster a resource and possibly help you out if you didn't have any potions before then. 

However, I think the idea you have in mind isn't too bad but still adds complexity I'd rather avoid.  Because I plan to implement abilities iteratively based on the level of the ability, I am hesitant to have that kind of complexity at that level.   All in all, that isn't a bad idea though.  

Any one else have any suggestions?

**Comment by BlackVegetable** [comment]
Regarding the replacement of:

Apply Salve
Cost: 7 AP
Effect: Healing; Apply a healing or status recovery potion from your inventory onto an adjacent ally.
Cooldown: 1x per turn

What about:

Reverse Hex
Cost: 10 AP
Effect: Dispel; Remove one random negative status effect from an ally or yourself if it is Arcane elemental.
Cooldown: 2 Turns (3 turns in program code.)
Range: 1 tile (melee)

It fits with the Wizard thematically.  It continues to be useful at later levels.  It doesn't totally negate the challenge of magical debuffing enemies as it has a decent cooldown and if used on an ally, requires you to be adjacent to them.  On the upside, it always works regardless of how powerful the debuff is.

**Comment by BlackVegetable** [comment]
Regarding the replacement of:

Swipe Potion (Active)
Flavor Text: Steal from the rich and give to the... thirsty.
Cost: 3 AP
Effect: Theft; If the target is carrying a potion of any kind, attempt to steal it and add it to your inventory. Typically only works on humanoids. Does not immediately consume potion. Chance of success = (Player Cunning - Target Cunning) \* 9%.
Range: Melee
Cooldown: 1 Turn

What about:

Chain Grasp
Cost: 6AP
Effect: Debuff; Throw a chain to wrap around and otherwise distract your foe.  If successful, will slow movement speed by 25%, give a 5% chance to fail casting spells, and lower dodge by 5.  Huge enemies are immune.  Chance of success =  (Player Cunning - Target Cunning) \* 9%, maximum = 90%.  
Cooldown: 6 Turns (7 turns in program code)
Range: 4 tiles
Duration: 3 Turns

It fits with the Thief thematically.  The dodge reduction is more useful early on than later, but will still be relevant.  The other effects are useful at all levels.  It works well to debuff any enemy type in a useful manner but isn't completely overpowered as a thief cannot use this ability very often at all and huge enemies are outright immune.  It is ranged so it doesn't force ranged thief classes like the Assassin and the Druid to close into melee to use it.  Best of all, I have a killer icon picked out for it!

**Comment by BlackVegetable** [comment]
Abilities replaced as suggested except the "Arcane" element requirement of Reverse Hex has been removed and replaced with +2 turns of cooldown.
