### ISSUE TITLE
Other methods of experience

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#7]
Should we have activities such as picking locks, disarming traps, exploring etc. give experience as well as killing monsters? If so, should the benefit of a rogue disarming a trap grant the experience to the entire party? Should we have locks at all?

Colton: We will definitely have locks, I don't know about lock-picking, though. As far as experience goes, I think it would be cool to have experience completely shared among your party as long as you were within 2 (arbitrary) screens of each other. Monsters would be scaled up enough that hopefully they wouldn't be able to both be winning battles at the same time, they'd have to cooperate. But I always hated getting experience differences with your friends while playing co op.

@jabelch

**Comment by jabelch** [comment]
I like the idea of some locks being pick-able, it would just take a predetermined set of time with monsters alerted to your presence or some other difficulty.  But we would also need some locks that are not able to be picked.

**Comment by BlackVegetable** [comment]
I would like some locks to have a lockpicking option, and others always require a key, as Josh suggested.  This gives another layer of depth to Thief and Wizard based classes (Wizards that can cast a spell to do the same job.)  Also, it could be tied to the Cunning stat, as that is still looking slightly underpowered.

The real question is whether we want to have experience be granted for various activities other than fighting.  I think we'll  all agree that the exp should be shared evenly.  But what activities should count?  Some options:
- Killing monsters (given)
- Unlocking a lock without a key
- Exploring a new region or type of region for the first time
- Completing a task for an NPC
- Disarming Traps
- Discovering Hidden Passages or Treasure
- Identifying an Item without the aid of a shopkeeper
- Uncursing a Cursed Item

(For those last two, visit the Cursed items page, which has recently changed.)

I am unsure I even want hidden passages and treasure to exist in the game.  I am also not sure we will have NPCs that give tasks.  Other than that, I vote all of the activities listed give experience, but that 80%+ of exp come from fighting monsters.

**Comment by malikoth** [comment]
Most things do give experience in Moria, but notably NOT exploring.  Discovering a hidden door or trap does, but not just walking around looking at things.  I like this system.

I kind of think that all doors should be unlockable, theoretically at least.  The door could require a tremendous cunning rating, or several tries to get it.  If you want to make it you have to fight a boss before you go through a door to get his weapon cache, you could sit the boss fairly close to the door and make sure he has enough perception to see the door.  If you come along, you can try to sneak along the wall, and then get it, grab loot, dodge around him, and run back out without entering true combat.  If you're stealthed, you can try to get in, but each attempt could have a chance of dropping stealth (rattling the lock to much, attracted boss's attention).  Could give the boss a charge ability if you want it to be practically impossible to get through door without fighting him.  But I basically think it should be _possible_ at least.

Party XP sounds fine to me.  Will comment a little more later.

**Comment by BlackVegetable** [comment]
I'm fine with that.  Exploration XP didn't appeal to me _much_ anyway.

**Comment by basepi** [comment]
No exploration XP, please.  Lockpicking is fine, and I suppose I don't want to restrict how people play, so we can just have high cunning requirements, as @Jzar has said.

**Comment by jabelch** [comment]
what about implementing actual puzzles?  I understand this would be a lot of work, perhaps we should keep it as an option for extra/bonus content.  The number and complexity of these would be a hurdle, unless we can come up with a relatively easy way to generate unique and progressively difficult "mini games"

I've always been drawn to games that have mini puzzles (like Zelda).

**Comment by malikoth** [comment]
I think true puzzles would be beyond the scope of this project, simply
because each one would have to be hand-crafted.  Unless you can figure out
a way to dynamically generate interesting puzzles.  I just can't think of
how I would write that algorithm.  Once they're crafted, then you could
randomly insert them in the game world, but you'd still have to craft it
yourself first, and I think that would take a lot of development time for a
minimum of benefit.

**Comment by basepi** [comment]
Right.  Puzzles are almost always hand-crafted (with maybe some randomized elements) and then put into the world at random.  (Like the phase portals in Torchlight 2)  This should be a 3rd-tier feature, which we can do if we have time.  It would be fun to add puzzles, but it takes time and is not necessary for a good game, necessarily.

**Comment by BlackVegetable** [comment]
Agreed.  The items that give experience are:

Killing monsters
Unlocking a lock without a key via any means
Disarming Traps
Discovering Hidden Passages or Hidden Treasure
Identifying an Item without the aid of a shopkeeper
Uncursing a Cursed Item

Is that correct? (Can we close the issue?)

**Comment by basepi** [comment]
Sounds fine.
