### ISSUE TITLE
Allow player to interact with monster in combat

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#71]
Probably single-class, no experience or anything else.  Keep it super basic.

**Comment by BlackVegetable** [comment]
Would you prefer we created a dummy for Alpha use, or should I try and pound out an actual PlayerCharacter instance before we meet.  (I could probably be at that point in a couple days.  I'm about 3 hours behind my own schedule atm and I've still got to get going on Networking!)

**Comment by basepi** [comment]
Reassigned this to @BlackVegetable, as he has taken over the main game loop.  Relevant to @Jzar as well.

**Comment by BlackVegetable** [comment]
Done.
