### ISSUE TITLE
Interact with PaneSwitcher objects

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#73]
When a player enters a tile with a PaneSwitcher object on it, we need to get the new tile, draw it, and place the player on it.

Will need PaneSwitcher objects from @jabelch before we can really make this enhancement.

**Comment by jabelch** [comment]
Do you mean get the new Pane, draw it, and place the player on it?

**Comment by jabelch** [comment]
No longer dealing with pane switcher objects
