### ISSUE TITLE
Picklock/Bash Chests

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#74]
Chests, etc?  Something else besides just PaneSwitcher.  Also need to settle on a model to handle these interactions.

FYI, @BlackVegetable.

**Comment by BlackVegetable** [comment]
We could jump to interacting with a Trap pretty quickly, as I have the necessary stuff down for a Trap object.  But... we'll want to represent our little character internally with a PlayerCharacter class first, which means I've got to write that constructor/loader and parser.

**Comment by basepi** [comment]
Reassigned this to Devin, since I handed off the main game loop.

**Comment by BlackVegetable** [comment]
This has come down to picking up items, putting down items (player trading... DONE!) opening/bashing/picking treasure chests, and disarming traps.  
Once we have treasure chests finished off (via @jabelch ) we'll need images for items to drop which Devin/Josh will work on I imagine, and then Devin/Josh will deal with disarming traps.

**Comment by BlackVegetable** [comment]
Treasure chest bashing/unlocking _might_ be done before Beta demo, however I'm 80% sure that traps will not be even placed.  Thus I'm moving this out of the Beta milestone.

**Comment by BlackVegetable** [comment]
Don't quite have enough time for this.  Moving it to next week's milestone.

**Comment by BlackVegetable** [comment]
Josh, chests are dissappearing as soon as they are interacted with.  I am not calling any form of remove method.  This needs to be changed so chests can be accessed without being removed from the server as well.

**Comment by jabelch** [comment]
Fixed.  I moved the call out of the get_chest function and explicitly call remove chest only after a chest is opened.

**Comment by BlackVegetable** [comment]
I've still got to finish this issue though.

**Comment by BlackVegetable** [comment]
@jabelch Thanks for your fix.  I was able to finish it, and it's pretty cool.  Gear in chests that are locked is ever so slightly stronger too (that is, until you damage the gear by bashing it!)
