### ISSUE TITLE
Treasure Chests on the Map

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#87]
I was thinking that whenever a group of monsters is defeated (indicated by a single monster icon in the overworld), it would drop a treasure chest on the location it was on previously.  This is fine, however, If another monster moves onto the same tile as a chest, enters battle with players (and dies), it will drop another chest on the same location.  I'm not sure we want that.  

Is there a different way to handle treasure chests and monsters dropping loot that you have in mind?  Or is there a simple fix to this "formula"?  Thoughts? @basepi @jabelch @Jzar

**Comment by basepi** [comment]
Maybe prevent monsters from moving onto chests?  Dunno.

**Comment by BlackVegetable** [comment]
That seems simple and reasonable.  Players might be able to board off monsters that way, but actually, that might just add an element of strategy to the overworld.  Let's plan on implementing that.
