### ISSUE TITLE
Informing the Players of details

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#88]
A lot of information may be lost on the players.  For instance, I have a monster that "Panics" when it gets low on HP and receives a melee attack.  This raises one of its statistics in a meaningful way.  However, this information will be hidden from the players as it isn't really a status effect.  (Even if it were, this issue extends to status effects in general...)

How can we convey to the player that certain abilities are being used, or what these abilities do?  Another example is a monster attack that deals bonus damage, and more importantly (and subtly) has bonus armor penetration.  How can we inform the players that these actions and these details are happening?

Having a game manual with some of this information would be nice, but I don't feel it is a good substitute for in-game information conveyance.  Any ideas? @basepi, @Jzar , @jabelch ?

**Comment by basepi** [comment]
We could perhaps have some reserved space on the right (where all the health bars will be) for arbitrary text to be shown.  "Kraken is enraged! (Strength +3)"

**Comment by BlackVegetable** [comment]
I think this question has been resolved.  I just need to implement adding such text at the proper moments (and basepi has to implement the text area.)

**Comment by basepi** [comment]
Text area is implemented.  Party on.
